### ISSUE TITLE
Create a change log

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#104]
It's good to create a change log for our project and list the changes in every release of CodingSpectator. We could manage such a change log simply by adding a file called `CHANGELOG.md` to the root of the repository.

**Comment by vazexqi** [comment]
I think this should be fine. It's even more important now that we have all our tasks assigned a particular version e.g. Version-0.2. We can just read off the tasks that are assigned to that particular version when we release.

We can start with Version-0.3.

**Comment by reprogrammer** [comment]
Resolved in eeb58ec2c90d77d3b3946d61362ec6ad1bad5a50.
