### ISSUE TITLE
Provide opportunity for user to correct username/password

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#11]
SVNKit provides a specialized exception when the user has entered a wrong username/password. We can use this to help prompt the user again for that info in the dialog box.

**Comment by reprogrammer** [comment]
The commit 60c6dcb5c112abd067c8f025dda339e5ba4bd114 addresses this issue partially. It makes the code prompt the user again for username and password, but it creates two other issues issues #20 and #21.
