### ISSUE TITLE
Identify users in combined log files

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#112]
We don't record user names in the XML logs files for refactorings. But, the user who has produced the log file can be identified by looking at the path of the log file in the file system.

When we consolidate log files of several users into a single XML file, we can no longer associate the refactorings back to the users easily. There are two ways to address this issue. First, we could just run the log consolidator on each user's directory separately to generate the combined log file for individual users. Second, we could add the information about users in the final XML file. To mark the refactorings performed by each user in the final XML file, we need to introduce a new tag. Specifically, we could use the XML tag `<user name="netid">...</user>` to wrap the refactorings performed by the user with netid "netid". The structure of the resulting XML would look like the following.

```
<sessions>
    <user name="netid">
        <session>
            ...
        </session>
    </user>
<sessions>
```

I think as long as we can manage a log file per user, we should use the first approach because it's simpler.

**Comment by vazexqi** [comment]
What is the approach that we will be taking: Consolidate a log file per user? Or a master log file? The sample XML that was sent earlier today consolidated everything together for convenience. In the future, if we get more participants, I think a log file per user would be more manageable: so I second the first approach.

Another question is how to we plan to handle all the different versions of CodingSpectator? This is not just a coding issue but more of a data analysis issue: how do we reconcile data from the first version of CodingSpectator that does not have rename monitoring with the later version which do?

For this second question, I think it is important to consolidate it with data from the performed refactorings through the default Eclipse mechanism and also Stas's tool. That way we have an idea of how many refactorings our tool failed to capture during the initial stages.

What do other people think?

**Comment by reprogrammer** [comment]
This issue is very old and we never combined XML logs of multiple users into a single XML file. So, I'm going to close this issue for the time being.
