### ISSUE TITLE
Do not upload during shutdown

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#121]
CodingSpectator shouldn't initiate an upload while Eclipse is begin shutdown.

UDC checks for the Eclipse shutdown and doesn't start to upload if Eclipse is being shut down.

**Comment by vazexqi** [comment]
Should be fixed in 93ae7fcb8473e966db15d181aa05337a882a674e

Not sure if we will ever encounter this scenario. We only upload on startup and also when the user clicks on the button. We don't periodically check for when to upload like UDC does (it checks each time a new batch of events come in).
