### ISSUE TITLE
Failed to install CodingSpectator from the update site

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#128]
I got the following error message when trying to install CodingSpectator v1.0.0.201101151513 
 from the update site into a fresh copy of Eclipse Helios SR1.

Surprisingly, I didn't experience this error message when I installed the same version of CodingSpectator form the local repository.

<pre>
An error occurred while collecting items to be installed
session context was:(profile=epp.package.rcp, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.apache.commons.codec.source,1.3.0.v20100518-1140
No repository found containing: osgi.bundle,org.apache.commons.httpclient.source,3.1.0.v201005080502
No repository found containing: osgi.bundle,org.apache.commons.logging.source,1.0.4.v201005080501
No repository found containing: osgi.bundle,org.eclipse.ecf.filetransfer.source,4.0.0.v20100529-0735
No repository found containing: osgi.bundle,org.eclipse.ecf.identity.source,3.1.0.v20100529-0735
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer.httpclient.source,4.0.0.v20100529-0735
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer.httpclient.ssl.source,1.0.0.v20100529-0735
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer.source,3.1.0.v20100529-0735
No repository found containing: osgi.bundle,org.eclipse.ecf.provider.filetransfer.ssl.source,1.0.0.v20100529-0735
No repository found containing: osgi.bundle,org.eclipse.ecf.source,3.1.0.v20100529-0735
No repository found containing: osgi.bundle,org.eclipse.ecf.ssl.source,1.0.0.v20100529-0735
No repository found containing: osgi.bundle,org.eclipse.equinox.frameworkadmin.equinox.source,1.0.200.v20100505
No repository found containing: osgi.bundle,org.eclipse.equinox.frameworkadmin.source,2.0.0.v20100503
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.artifact.repository.source,1.1.1.R36x_v20100901
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.console.source,1.0.200.v20100601
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.core.source,2.0.2.R36x_v20100804
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.director.app.source,1.0.201.R36x_v20100823
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.director.source,2.0.2.R36x_v20100823
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.directorywatcher.source,1.0.202.R36x_v20100727
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.engine.source,2.0.0.v20100606
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.extensionlocation.source,1.2.0.v20100518
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.garbagecollector.source,1.0.100.v20100503
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.jarprocessor.source,1.0.200.v20100503a
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.metadata.generator.source,1.0.200.v20100503a
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.metadata.repository.source,1.1.0.v20100513
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.metadata.source,2.0.0.v20100601
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.operations.source,2.0.0.v20100510
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.publisher.source,1.1.2.v20100824-2220
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ql.source,2.0.0.v20100503a
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.reconciler.dropins.source,1.1.0.v20100525
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.repository.source,2.0.1.R36x_v20100823
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.repository.tools.source,2.0.1.R36x_v20100823
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.touchpoint.eclipse.source,2.0.2.R36x_v20100823
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.touchpoint.natives.source,1.0.200.v20100503a
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui.sdk.scheduler.source,1.0.0.v20100507-1815
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui.sdk.source,1.0.100.v20100513
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.ui.source,2.0.0.v20100518
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.updatechecker.source,1.1.101.R36x_v20100823
No repository found containing: osgi.bundle,org.eclipse.equinox.p2.updatesite.source,1.0.201.R36x_v20100823
No repository found containing: org.eclipse.update.feature,org.eclipse.equinox.p2.user.ui.source,2.0.1.r361_v20100903-897HFZFFZRuSD2LMtVxyz0Vr
No repository found containing: osgi.bundle,org.eclipse.equinox.simpleconfigurator.manipulator.source,2.0.0.v20100503
</pre>

**Comment by reprogrammer** [comment]
I repeated the installation on another fresh instance of Eclipse Helios SR1 with the same version of CodingSpectator. Surprisingly, the exception didn't occur.

**Comment by vazexqi** [comment]
I did _not_ get this error while trying to install it earlier today.
