### ISSUE TITLE
The "Java" and "Plug-in Development" perspectives are not available

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#131]
I installed CodingSpectator v1.0.0.201101151513 from the CodingSpectator update site on a fresh instance of Eclipse Helios SR1. But, the "Java" and "Plug-in Development" perspectives are not available. It looks like there is some problem in loading the JDT plugin.

Note that this problem doesn't happen when I install the same version of CodingSpectator from a local update site.

**Comment by reprogrammer** [comment]
I noticed that the size of `org.eclipse.jdt.ui_3.9.0.201101151513.jar` at the update site is 9.4MB. But, the size of this jar file in the `plugins` directory of my Eclipse is only 1.9MB.   When I try to open the jar file installed in my instance of Eclipse, I get the following error message.

<pre>
Archive:  org.eclipse.jdt.ui_3.9.0.201101151513.jar
[org.eclipse.jdt.ui_3.9.0.201101151513.jar]
  End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive. In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.
zipinfo: cannot find zipfile directory in one of org.eclipse.jdt.ui_3.9.0.201101151513.jar or org.eclipse.jdt.ui_3.9.0.201101151513.jar.zip, and cannot find org.eclipse.jdt.ui_3.9.0.201101151513.jar.ZIP, period.
</pre>

**Comment by reprogrammer** [comment]
I cannot download the complete jdt.ui jar file directly from the github repository. But, I get can get the whole file using `git clone`.

**Comment by reprogrammer** [comment]
I used the following command to download the jdt.ui jar file.

```
wget https://github.com/codingspectator/codingspectator.github.com/raw/master/updates/plugins/org.eclipse.jdt.ui_3.9.0.201101151513.jar --no-check-certificate
```

But, it fails to download the complete jar file and reports the following message.

```
Connection closed at byte 4672000. Retrying.
```

Note that I experience the above error message only when I run the `wget` command on my laptop at home not at my machine at the office.

**Comment by vazexqi** [comment]
I have the same problem from my home machine - I lost the Java and Plug-in Development perspectives. I also confirm that size of `org.eclipse.jdt.ui_3.9.0.201101151513.jar1 is wrong. For me it was only 648 KB and I cannot unarchive it either.

But if I issue the wget command, I am able to download the file completely.

**Comment by reprogrammer** [comment]
I published the Eclipse update site on my home page. And, I was able to install CodingSpectator from this mirror. This confirms that we're facing a problem in GitHub.

**Comment by reprogrammer** [comment]
I reported the problem we're experiencing with the our Eclipse update site hosted on GitHub pages to [support.github.com](http://support.github.com).

**Comment by vazexqi** [comment]
Did you make the problem public or private? I can't find the particular thread.

**Comment by reprogrammer** [comment]
I made it public at [http://support.github.com/discussions/site/2535-github-pages-have-stopped-to-function-as-my-eclipse-update-site](http://support.github.com/discussions/site/2535-github-pages-have-stopped-to-function-as-my-eclipse-update-site).

**Comment by reprogrammer** [comment]
I successfully installed CodingSpectator v1.0.0.201101161822 on a fresh instance of Eclipse Helios SR1 at the office.

But, when I used the GitHub update site to update an instance of CodingSpectator v1.0.0.201011241830 that was installed on my Eclipse Helios SR1 at the office, I got a message saying that some of the jar files of CodingSpectator are not unsigned. And, I assume this message to mean that it couldn't download the jar files from the GitHub mirror correctly. Surprisingly, I get the same unsigned warning dialog when I try to update CodingSpectator from the mirror of the Eclipse update site hosted on my home page. I get the same warning dialog when I try to install from a local update site. So, I conclude that there is a problem with signing the jar files. Therefore, I'm going to investigate it further in issue #133.

**Comment by reprogrammer** [comment]
Tekkub has responded to [our site issue](http://support.github.com/discussions/site/2535-github-pages-have-stopped-to-function-as-my-eclipse-update-site):

> Pages isn't designed for hosting binaries, you should put those in your repo's downloads section or on some bulk-rate service like Amazon S3.

I'm not familiar with the downloads section of GitHub repositories. We need to consider moving our Eclipse update site to the downloads section per GitHub's recommendation.

**Comment by vazexqi** [comment]
Ok. I know of the "Downloads" section but I wasn't aware that there was throttling for binaries on the pages. He did not answer the question - he just suggested a solution so we still do not know what the problem is.

We should definitely move it over to download section. Ideally we should host it on the university servers.
