### ISSUE TITLE
Import documents from the internal wiki into the GitHub wiki

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#136]
We need move to some of the documents such as our coding conventions to github.

**Comment by reprogrammer** [comment]
Moved the instructions for contributing to the project to [Contributing to CodingSpectator](https://github.com/vazexqi/CodingSpectator/wiki/Contributing-to-CodingSpectator).

**Comment by vazexqi** [comment]
Thanks for porting it over. I noticed that the wiki has problems rendering list > 10 items. The first digit goes missing. I have reported this [issue](http://support.github.com/discussions/site/2624-markdown-renderer-doesnt-handle-lists-10-items-well-on-wiki).

**Comment by reprogrammer** [comment]
@vazexqi: The markdown problem with rendering lists seems to be back. See https://github.com/vazexqi/CodingSpectator/wiki/Test-Markdown-Rendering-of-Lists
