### ISSUE TITLE
Make UI tests examine the data recorded by CodingSpectator

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#138]
Currently, the automated UI tests just check that whenever a refactoring gets canceled or performed, CodingSpectator records somethings. But, the tests don't check the contents of the actual data captured by CodingSpectator. We need to make the tests perform stronger checks. For example, the test should check the existence of certain attributes or even check the value or format of the values of some of the attributes. If the tests check the contents of the recorded data, we will have more confidence in the correctness of CodingSpectator.

We can write an XQuery script to check the contents of the captured data and use [Saxon HE 9.3.0.4 for Java](http://downloads.sourceforge.net/project/saxon/Saxon-HE/9.3/saxonhe9-3-0-4j.zip?r=http%3A%2F%2Fsaxon.sourceforge.net%2F&ts=1295996172&use_mirror=cdnetworks-us-1) to run the script on the XML file generated by CodingSpectator.

**Comment by reprogrammer** [comment]
Verified the descriptor logged for an unavailable extract interface refactoring in 8d3a1874c7ea9a1872b8950702f1486ee9a4ae3c. We didn't use XQuery to examine the contents of the XML log files. Rather, we used Eclipse to create refactoring descriptor objects from the XML files.

**Comment by reprogrammer** [comment]
I made mistake and put the issue number 163 in commit 8d3a1874c7ea9a1872b8950702f1486ee9a4ae3c instead of 138. What is the best way to fix it?

**Comment by vazexqi** [comment]
I did it the _BAD_ way and push an ammended git commit. You would need to delete your local branch and track the one from origin again.

**Comment by reprogrammer** [comment]
I deleted the branch "verify-captured-log" and checked it out again to get the corrected commit 69aad6c13364ce39e7ddd07289976a60dac2c8aa.

**Comment by reprogrammer** [comment]
Verified the code snippet of a refactoring descriptor in f9c915699c51e5bb7ff2b8d572a2cd9f29523d82.

**Comment by reprogrammer** [comment]
Verified the captured descriptor for an unavailable extract superclass refactoring in 75ce7920f7eb8a953f58afdf2dc9bfd55ab0caa9.

**Comment by reprogrammer** [comment]
Verified all of the fields of the captured descriptor in cef7da61f33777abdf5fb670efc51f71d8585338.

**Comment by reprogrammer** [comment]
bbabadaa6a9c49dfd0017d88caa6115a0c03dba1 merged "master" into "verify-captured-log" to switch to the new mechanism for locating the watched directory.

**Comment by reprogrammer** [comment]
Refactored the tests in 8a4f82210ce20d7b5e9ef8431ad6cf83b9e44328, 949e89641d79d6c871fabd6fede1921af93959c3 and 0de390e36f3dbe59cfe289bf93a0111ef2357047.

**Comment by reprogrammer** [comment]
595fda0e387470dfc119697a20b9073b5ee2c361 added verifications for an unavailable push down test.

**Comment by reprogrammer** [comment]
Verified the refactoring descriptor captured for an unavailable extract method refactoring in f45949d8ecab0027711077e1b1f7d6914134e7dd.

**Comment by reprogrammer** [comment]
b97a6bd145066ab86c667dd187399aa6cda186cd verified the descriptors captured for valid/invalid performed/canceled extract method refactorings.

**Comment by reprogrammer** [comment]
Verified the contents of the refactoring descriptors that CodingSpectator logs in the tests for the inline constant refactoring in 16a0ed50c14bf39e0071085527e98764dca293e4 and 6d35bcca63cea1e9603863006b0f32f28e1fcd5e.

**Comment by reprogrammer** [comment]
Improved the tests for the extract method refactoring in 98364ee3b2536f0116f2a3f1fb6e6655d98495fd.

**Comment by reprogrammer** [comment]
cade1cea897c49c5364292112f654f0db3053f58 verified the descriptor captured for a cancelled extract constant refactoring. And, c196149b36c64dc5d7e76c866fccf5ef8fdf1433 verified the descriptor captured for a performed extract constant refactoring.

**Comment by rajkuma1** [comment]
Added additional checks for verifying the XML file for MoveCompilationUnitToContainerTest in  15d3ff2650aeca66609066f2c827fab922cc7f1f .. 0e9309ef0caa04548ec2eab3a80a9a9767b85fec.

**Comment by reprogrammer** [comment]
Verified the descriptor captured by ValidCancelledExtractInterfaceParentClassTest in 8526e79a9e954cd2d7ff8eff103c26474800a928 and c87e36e9de3afe0681a65ef0d9c574d04322c994.

**Comment by reprogrammer** [comment]
Verified the descriptors captured for the rest of extract interface tests in b4c24c68d6b1585d7b0f3209a4790a76bfdf77e0 .. 751bbf548036399c7bbeaa0181b6b9cea3f32e74.

**Comment by reprogrammer** [comment]
28187a92bb4378ddd8956edbc67b28f40a11ccad and edd95b5f2063ab14bfa8589e77140a3ee7a0b545 verified the captured refactoring descriptor for `InvalidCancelledExtractSuperclassTest`.

**Comment by reprogrammer** [comment]
5cd7b3d4430ac27ef5e8a4787b0d9d854573b674 and a5b05f621c897f6056bfcbfce226e752a0a53c6d verified the refactoring descriptor for `ValidCancelledMultiStepExtractSuperclassTest`.

**Comment by reprogrammer** [comment]
e5a20342a59cfb929eece00b232a354023ca0a2f, 1072ef79f6a032a5bfeaa465186cc1866c10d2c9 and 14f38f0c65bce70c251f2eec6c4c25439c2f302d verified the descriptors captured in `ValidCancelledSingleStepExtractSuperclassTest`, `ValidPerformedMultiStepExtractSuperclassTest` and `ValidPerformedSingleStepExtractSuperclassTest`.

**Comment by reprogrammer** [comment]
f649dc55659a37b86fb170f69b7d9397d8269b1e .. 3e6c220c7d0c5060e43d752bd1e7c04ac94d48f8 simplified the verification of the captured descriptor in extract constant tests.

**Comment by reprogrammer** [comment]
9a47970a0dc6e3900a1d8afcc4064e69dc47fe5a .. e01a8ccb4620732cc2e236492979fb87eb3cbee1 refactored the tests for the extract interface to verify the correctness of captured refactorings using the new file comparison based technique.

**Comment by reprogrammer** [comment]
4c8762897b981540e35a3466c356880d523b6f58 .. 56b500f976d81ca27b5796f63659853005f044e6 refactored the tests for the extract method refactoring to the new file comparison based technique for verifying the contents of the captured descriptors.

**Comment by reprogrammer** [comment]
5e5ed652b346c3305bbd8fd9ed64ba539412daee .. 75ede286581ee3adc65a9c26aad2a965599f101a refactored the tests for the extract superclass refactoring to use file comparisons to check the correctness of captured refactoring descriptors.

**Comment by reprogrammer** [comment]
c2c688a89f86dec31d6b3e5f29b9351786f29ff2 .. 8f8035a708ab8127c0d652915266ee4beaa47533 refactored the tests for the inline refactorings to check the captured descriptors by comparison with expected files.

**Comment by reprogrammer** [comment]
1d19b24f81c7035c780ca8cd999af5d3dc567230 refactored ValidCancelledMoveCompilationUnitToContainerTest for file based comparison of descriptors.

**Comment by reprogrammer** [comment]
11163b110f3ef9797ee6dec334a8fe1a2219ded9 refactored UnavailablePushDownFieldTest to comparison of descriptor files.

**Comment by reprogrammer** [comment]
0230bd8f0dd1bb0df9323eb54813235de6e84080 refactored UnavailableRenameKeywordTest for comparison of descriptor files.

**Comment by reprogrammer** [comment]
11c868787969aa9b75ecad5253cb719c92cce01e made it possible to remove some code duplication by pulling up the logic for verifying refactoring descriptors to `RefactoringTest`.

**Comment by reprogrammer** [comment]
8b9a223596d94b8e6ddf8741a98c4c7cb8aef0b1 and 894c0c6562969b14184b56e24d9442b92574ff89 improved the two remaining tests of the extract constant refactoring to reuse the infrastructure in `RefactoringTest` to verify the captured refactoring descriptors.

**Comment by reprogrammer** [comment]
bf820e51b465fe5138317c4e6eb88d012ba8d020 .. a34d298179b4f6379e8802ae433a86c3669fe702 improved the following tests by removing some code duplication and reusing `RefactoringTest` for checking the captured descriptors.
- extract interface
- extract method
- extract super class
- inline
- `ValidCancelledMoveCompilationUnitToContainerTest`
- `UnavailablePushDownFieldTest`
- `UnavailableRenameKeywordTest`

**Comment by reprogrammer** [comment]
Currently, the following tests do not verify the contents of the captured refactoring descriptors.
- move
- pull up
- push down
- rename
- use super type

I've pulled up some of the code for verifying the contents of descriptors to `RefactoringTest` to make it more reusable. This refactoring has made it even easier to verify the descriptors. Simply, we need to override the method `edu.illinois.codingspectator.ui.tests.RefactoringTest.getRefactoringLogCheckers()` and add the expected descriptors to the `expected-refactoring-descriptors` folder in order to check the contents of captured refactoring descriptors.

**Comment by rajkuma1** [comment]
Cleanup of ValidCancelledMoveCompilationUnitToContainerTest in 128089bdb1bb86d25aafdd08e3ffbcb9eda44d6e.

**Comment by rajkuma1** [comment]
Updated InvalidCancelledMoveInstanceMethodTest to follow the new style of descriptor verification in 891325f02df03c69d5c98c3be4e5cea23c4d787e.

**Comment by rajkuma1** [comment]
Updated InvalidCancelledMoveStaticFieldTest  to follow the new style of descriptor verification in 5400a39501927dbccab4289fa22b98c31e7b703b.

**Comment by rajkuma1** [comment]
Updated InvalidCancelledMoveStaticMethodTest  to follow the new style of descriptor verification in eadbe175ee1f583600906ce01e94b5945efa1bcf.

**Comment by reprogrammer** [comment]
@rajkuma1, please override `edu.illinois.codingspectator.ui.tests.RefactoringTest.getRefactoringLogCheckers()` instead of manually comparing the descriptors. See the tests for the extract constant refactoring as an example of how to use the new API for verifying captured descriptors.

**Comment by rajkuma1** [comment]
@reprogrammer: Alright. I'll update the tests.

InvalidPerformedMoveInstanceMethodTest fails since it has 2 refactoring descriptors.
The one containing project=null is extra.
Descriptior set in case of:

# InvalidPerformedMoveInstanceMethodTest:

[org.eclipse.ltk.internal.core.refactoring.history.DefaultRefactoringDescriptorProxy[stamp=1300644069505,project=null,description=Move Method], org.eclipse.ltk.internal.core.refactoring.history.DefaultRefactoringDescriptorProxy[stamp=1300644069635,project=TestProject_class edu.illinois.codingspectator.ui.tests.move.InvalidPerformedMoveInstanceMethodTest,description=Move method 'm3']]

# InvalidCancelledMoveStaticFieldTest:

{org.eclipse.ltk.internal.core.refactoring.history.DefaultRefactoringDescriptorProxy[stamp=1300644499367,project=TestProject_class edu.illinois.codingspectator.ui.tests.move.InvalidCancelledMoveStaticFieldTest,description=Move member 'field']=java.lang.Object@69e017e4}

**Comment by rajkuma1** [comment]
This is a problem even with the correct structure for InvalidPerformedMoveInstanceMethodTest.

**Comment by rajkuma1** [comment]
Fixed ValidPerformedMoveStaticMethodTest to follow the new style of descriptor verification in  ce891183f1b210d38f2d9a850b5b6dbe1fc837f9.

**Comment by rajkuma1** [comment]
Fixed InvalidCancelledMoveInstanceMethodTest in d228240b5a071b765d9194cb8f5d62d677b6243d.

**Comment by rajkuma1** [comment]
Fixed InvalidCancelledMoveStaticFieldTest to use getRefactoringLogCheckers in 94618bdfb76d65b8900a93c4138cf08537800212.

**Comment by rajkuma1** [comment]
Fixed InvalidCancelledMoveStaticMethodTest to use getRefactoringLogCheckers in f86909ee29b830a3cb4f5ad174d9b3e2ff231013.

**Comment by rajkuma1** [comment]
Here's a failure trace due to 2 descriptors instead of 1:

java.lang.AssertionError: expected:<1> but was:<2>  
    at org.junit.Assert.fail(Assert.java:91)
    at org.junit.Assert.failNotEquals(Assert.java:645)
    at org.junit.Assert.assertEquals(Assert.java:126)
    at org.junit.Assert.assertEquals(Assert.java:470)
    at org.junit.Assert.assertEquals(Assert.java:454)
    at edu.illinois.codingspectator.ui.tests.RefactoringLogUtils.getTheSingleRefactoringDescriptor(RefactoringLogUtils.java:33)
    at edu.illinois.codingspectator.ui.tests.RefactoringLogChecker.assertMatch(RefactoringLogChecker.java:43)
    at edu.illinois.codingspectator.ui.tests.RefactoringTest.doRefactoringShouldBeLogged(RefactoringTest.java:56)
    at edu.illinois.codingspectator.ui.tests.RefactoringTest.refactoringShouldBeLogged(RefactoringTest.java:95)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.swtbot.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:64)
    at org.eclipse.swtbot.eclipse.core.UITestApplication.runTests(UITestApplication.java:117)
    at org.eclipse.ui.internal.testing.WorkbenchTestable$1.run(WorkbenchTestable.java:71)
    at java.lang.Thread.run(Thread.java:662)

**Comment by rajkuma1** [comment]
Added failing test for Mohsen to debug in db318e5bbecabd74e14f8882c536f513cacba734.

**Comment by reprogrammer** [comment]
e8fe479cd69d76e81e4ea5132d567860bf053f7f merged the descriptor verifiers for some of the refactorings.

**Comment by reprogrammer** [comment]
@rajkuma1

Tests that override `edu.illinois.codingspectator.ui.tests.RefactoringTest.getRefactoringLogCheckers()` do not need to declare a field of type `RefactoringLog`. Please see 158bf4028e4002c7432660d21e248c168d662fd8.

**Comment by reprogrammer** [comment]
rajkuma1 updated the following tests to verify the descriptors.
- ValidPerformedMoveCompilationUnitToContainerTest: 83f3e49bb208db14db3ebd6c1d20d5059308a3ab.
- ValidPerformedMoveCompilationUnitTest: c37a46cf3a4f0a0c01eb55ef361d175755737cac
- ValidCancelledMoveStaticMethodTest: 870c1e2427f41d6fc5bdce290c738778fffa4323
- ValidCancelledMoveStaticFieldTest: 5bf1751d9509992dc56a284eb6190a839451d548
- ValidCancelledMoveInstanceMethodTest: 860fa5ab475c605e9a9148d3352240d049466dfe
- ValidPerformedMoveStaticFieldTest: 7aaee7151d2def7763e6d84cd57dc001b8485e49
- ValidCancelledMoveCompilationUnitTest: 15d3dd7bfc7e536c99d2c8df74b2a995adc07931
- InvalidPerformedMoveStaticFieldTest: 620bdbec771f20ef3c3a3cf590c9d144889b2281
- InvalidPerformedMoveStaticMethodTest: f97e0daea496b2c962b5c80d11f0366f6625e5b3

**Comment by reprogrammer** [comment]
Please refer to issue #181 for more details about the problem reported in [one of the comments above](https://github.com/vazexqi/CodingSpectator/issues/#issue/138/comment/895855).

**Comment by rajkuma1** [comment]
Updated pull up refactoring tests to verify XML descriptors in 29bc278686ed406326f0c8156c0165dee736c48f .. 6b784124afe7e7f95aa0575ab75ca42df3899a07.

**Comment by rajkuma1** [comment]
Updated README for pullup tests with mappings between new and old test files in f7e3c91c3df665631f390cbb055555734d9cb075.

**Comment by reprogrammer** [comment]
Removed `getRefactoringLogCheckers` from all tests in 28d91b90516bb748777ec5c0f5ea5fee4608d68d.

**Comment by reprogrammer** [comment]
18ae9bf3be2fb5063bad56a6e07c6ca91ca5f2ee added expected refactoring descriptors for the remaining refactorings.
