### ISSUE TITLE
Update the user's guide

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#147]
We have to update the user's guide to reflect the updated installation process. We have self-signed the jars. So, the user will see a dialog that asks if the user trusts our certificate. The user should no longer see the dialog that warns about unsigned content. In fact, if the user sees the warning about unsigned content, it means there are some problems with the installation.

Also. it would be nice to convert our user's guide into HTML. We can send links to specific sections of the user's guide based on the user's actual needs.

**Comment by reprogrammer** [comment]
7bc7e053dfc305c4b017f2766aba282762ae4e3b contains the first LaTeX version of the user guide.

We need to make the following changes to the user's guide.
1. The user's guide is directed towards CS427 students. We need to target a broader audience.
2. The way that I've included images is only good for [hevea](http://hevea.inria.fr/). We need to make it processable by pdflatex as well. (a5054289d0075c9a908345db2ea56571fd724316 fixed this problem.)
3. Since we've signed our plugins, we should tell the user to trust our certificate and make sure that he/she doesn't get the security warning about unsigned content.
4. Stylize the document a bit to make it look nicer. (2860adbcf4fc135e8a50167890327c2929d19b66 fixed this problem.)
5. Make URLs hyperlinks in the generated HTML. (9b17d6a2f6615b70b1bcf42655032bd31431bf11 fixed this problem.)

**Comment by vazexqi** [comment]
Since we are also going to create a new plug-in for logging (see #149) I probably have to generate new screenshots of the installation page to show the selection of that plug-in as well. So I will wait until that part is ready before generating the images.

**Comment by reprogrammer** [comment]
Updated the first two sections in b80281409bdb7ce6a1e85dd079f700b7d239e68b and 39397b0a24f1804b3168f024601ba464eefd4546.

**Comment by vazexqi** [comment]
Added updated screenshots in bcfcd270c85182887e7a9da397744eec5e2fede7

**Comment by reprogrammer** [comment]
Revised section 3--8 in c09c101ddbb4f7bfb6d99de2fe5a338087179da5.

**Comment by reprogrammer** [comment]
Merged the branch `user-guide` into `master` in 2c4778dc25e5e2c996dca2faf36d835703b15c92.

**Comment by reprogrammer** [comment]
We need to explain in the user guide the options CodingSpectator adds to UDC.

**Comment by reprogrammer** [comment]
Updated the contact information in 2c4fe9216a7c504c8e6b28d0f788fc2ba26cdafa.
