### ISSUE TITLE
Push Down Refactoring tests

### ISSUE THREAD

**Issue by rajkuma1** [vazexqi/CodingSpectator#152]
Write tests for push down refactoring.
Cover cases for valid / invalid and cancelled refactorings.

**Comment by rajkuma1** [comment]
I've created this issue to track the testing effort. We have scheduled to work on the implementation tomorrow. I want to write tests by then.

**Comment by reprogrammer** [comment]
I've created the branch `instrument-push-down`. Please add the tests for the push down refactoring to this branch.

**Comment by reprogrammer** [comment]
Added Balaji's tests in ec9145a1da248d0a73d02749ef1d41fddd8d2a50.
