### ISSUE TITLE
Instrument push down refactoring

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#153]
We expect the push down refactoring to be similar to pull up and extract superclass refactorings.

We'll capture unavailable, performed and canceled events of the push down refactoring in branch `instrument-push-down`.

**Comment by rajkuma1** [comment]
ok. The tests won't run completely. Shall I check them in anyways?

**Comment by reprogrammer** [comment]
What do you mean by not running completing? Does that mean that the tests fail? If they fail, do they fail because we have captured push down yet? If the failure is because we haven't instrumented the push down refactoring yet, it's OK to check in the tests into the branch.

**Comment by rajkuma1** [comment]
I was referring to the case where my tests fail because the instrumentation is not done yet. Thanks.

**Comment by reprogrammer** [comment]
a451e4ac64cb3c5e5077e7a736002c2f2367137e and 9818a3cccc234b9d6a67e0b4c9ebd8ded27c83d4 are the first commits to instrument push down.

We noticed that the current instrumentation fails to capture the latest selections. For example, if the user invokes the refactoring on a field `f`, and then deselects it from the push down dialog, the captured refactoring still says that the user had selected field `f`. We added a test (`CancelledDeselectAllPushDown`) to demonstrate this problem. But, because we don't check the contents of the XML at the moment, the test cannot detect the problem with the captured information.

**Comment by vazexqi** [comment]
Captured changes in the selection of the UI in 6fa99594db68a40e6ad0a6ac0332be619f9a1856 by forcing an update to the fMembersToMove array.

Finished instrumenting push down refactoring in 6fa99594db68a40e6ad0a6ac0332be619f9a1856 where we captured the unavailable refactorings.
