### ISSUE TITLE
Update the messages in the user interface

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#155]
The current messages in the user interface are tailored for CS427 students. Therefore, the messages refer to TSG and NetID. We need to update these message for a broader audience.

**Comment by vazexqi** [comment]
Fixed in 917cb5f9575c5d6eaec4d99ca4f57eaf1e41953f

**Comment by reprogrammer** [comment]
Updated `Messages.java` in ebe6617fd4a21493d9c63d10917ffc7ee39ccb67.
