### ISSUE TITLE
Include link to our FAQ & user guide in the submission dialog

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#172]
It would be nice to have direct links to our FAQ and user guide in the submission dialog. That way if the user has any questions or concerns he can click on the link immediately.

The UDC dialog [`AskUserUploaderWizard`](https://github.com/vazexqi/CodingSpectator/blob/master/org.eclipse.epp.usagedata.ui/src/org/eclipse/epp/usagedata/internal/ui/wizards/AskUserUploaderWizard.java) already does this and we can take a look at it.

**Comment by reprogrammer** [comment]
`SelectActionWizardPage` renders the hyperlinks using `org.eclipse.ui.forms.widgets.FormText`, and opens the URL whenever the listener registered by `org.eclipse.ui.forms.widgets.FormText.addHyperlinkListener(IHyperlinkListener)` gets notified.

**Comment by vazexqi** [comment]
60e5ae82cb10ca650c4840a8c727edaf92d96735 uses the same method as [`SelectActionWizardPage`](https://github.com/vazexqi/CodingSpectator/blob/master/org.eclipse.epp.usagedata.ui/src/org/eclipse/epp/usagedata/internal/ui/wizards/SelectActionWizardPage.java)

To change the message, please follow the convention in the [messages.properties](https://github.com/vazexqi/CodingSpectator/blob/master/edu.illinois.codingspectator.monitor.ui/src/edu/illinois/codingspectator/monitor/ui/messages.properties) file. I am not sure if we need to wrap them in `<form>` tags but I was just following the way UDC does it.

**Comment by reprogrammer** [comment]
The link in the submission dialog points to the page for changing the password not FAQ or the user guide, right?

**Comment by vazexqi** [comment]
Correct. I didn't know what you wanted to include so I just used what we had. Only the `AuthenticationPrompter_DialogDescriptionForReenteringAuthenticationInfo` property had the URL so that was the one that I converted.

Feel free to modify the different prompts as you see fit. I've just created the code for making this possible but did not change the contents yet.

**Comment by vazexqi** [comment]
Addressed an issue where the username field may receive focus even if it is not enabled in 6c3d08d60cf70350e69aef67bd32e51800c5d550
