### ISSUE TITLE
CodingTracker seems to ignore rename source folder refactorings

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#176]
I loaded the CodingTracker file at "P1/04cba2b6-8892-4008-8526-19026df460c1/1.0.0.201011031917/codingtracker/codechanges.txt". There are two rename source folder refactorings at the beginning of the sequence of changes [1289356504512, 1289356544088]. However, replaying these refactorings doesn't have any effect on the workspace. The first operation that causes some changes to the workspace is the "New file" operation at 1289359476236.

**Comment by Wanderer777** [comment]
This scenario is covered by issue #203. If the source folder exists in the replaying environment (e.g. a CompilationUnit was created in it), then the rename refactoring would be reproduced by moving the folder. If the folder does not exist yet, the moving operation (obviously) would not have any effect.
