### ISSUE TITLE
Capture the events for the Inline Method

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#18]

**Comment by vazexqi** [comment]
I have abstracted some of the common methods for creating RefactoringDescriptors for both Extract Method and Inline Method into a new class WatchedRefactoring in the jdt.core packages.

So far our method is generalizable to these two refactorings.

The code is in 953784cf458ad3260899ed2a096c8502c0e51b42

**Comment by reprogrammer** [comment]
96370398a5ab909b02e26d1881582350af23f702 and 2fb3e05f3492f39742d87543ae2dd9b4f134aa52 captured a possible unavailable instance of inline method in class `InlineMethodAction`.

**Comment by reprogrammer** [comment]
bc0605731d44a557a947e24a2f9b875236aba71b captured unavailable inline method refactorings found in `InlineMethodRefactoring.checkInitialConditions`.
