### ISSUE TITLE
Include the name of the test when reporting errors during testing

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#183]
We need to mention the name of the test when reporting an error message. This allows to easily identify the test causing the problem by reading the error message.

**Comment by reprogrammer** [comment]
Added the method `edu.illinois.codingspectator.ui.tests.RefactoringTest.printMessage(String)` in 5c6653446e89647a90e70caa27e7a82e57074a9e. Please use this method for reporting problems in the tests.

**Comment by rajkuma1** [comment]
Updated pullup/T01 to use `printMessage` instead of using `System.err.println` in under  in e4efb6df52de8522fcf3e47b0b4d69f3d91aea78.
