### ISSUE TITLE
Ignoring the certificate may lead to confusion

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#209]
One of our participants had a problem today installing CodingSpectator. I asked the participant to install CodingSpectator in front of me. As a result, I noticed that the participants pressed the "OK" button on the [certificate dialog](http://codingspectator.cs.illinois.edu/resources/installation/figs/certificate.png) without marking the check box. Consequently, Eclipse stopped installing CodingSpectator without telling the user that the installation had terminated because of the untrusted certificate. Note that when the installation terminates in such a way, Eclipse downloads the JAR files of CodingSpectator into Eclipse. But, the installation is not complete. This leads to even more confusion as why CodingSpectator is not installed even though its JAR files are copied. 

What are your suggestions to prevent this problem from confusing other users?

**Comment by vazexqi** [comment]
I don't know how we can solve this. This requires that the user check the checkbox. There is no default way to force this (this is a security issue).

You can try warning the user in the user guide but I am not sure how many people would read it. If it happens again, we should just mention that they need to accept the certificate in the recruitment e-mail that we send (and maybe include a screenshot).
