### ISSUE TITLE
Undoing Rename and Move refactorings results in NullPointerException

### ISSUE THREAD

**Issue by Wanderer777** [vazexqi/CodingSpectator#210]
Steps to reproduce:
1. Create a Java project and CompilationUnit in it. 
2. Rename (or Move) this CompilationUnit
3. Undo the above refactoring (e.g. use Ctrl+Z)

As a result, you will see an Eclipse error message saying "Abnormal Workbench Condition java.lang.NullPointerException". It looks like undoing any refactorings that manipulates with resources would result in this problem.

**Comment by Wanderer777** [comment]
This problem appeared since the commit f68604b3e22b5fb8ce1d45e8d1e11889fc895db4. It is due to making affected compilation units to become working copies (call to `CompilationUnit#becomeWorkingCopy()`) in method `RefactoringProblemsListener#makeAffectedCompilationUnitsBecomeWorkingCopies()`. Removing this call fixes the above problem. If removing this call breaks the refactoring problems logger, then we need to find a way to replace this functionality with something else.

**Comment by reprogrammer** [comment]
Here is why we make the compilation unit become working copy:

Comment the instruction that forces the compilation units to become working copies. Then, create the following two classes `C1` and `C2`:

```
class C1 {
   int a;
   void m() {
      ++a;
   }
}

class C2 {
}
```

Make sure that the editor of `C2.java` is closed. Now, if you move the field `a` from `C1` to `C2`, CodingSpectator won't capture the compilation problems.
