### ISSUE TITLE
CodingSpectator captures wrong selection information for a move refactoring

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#216]
CodingSpectator captures wrong selection information for a move refactoring that is invoked from within the editor.

Create a Java project called `P` with two files `C.java` and `D.java`:

**C.java**

```
public class C {

    int a;

    void m() {
        a++;
    }

}

```

**D.java**

```
public class D {

}
```

In the Java editor of file `C.java`, select the string `"a"` in the variable declaration `int a`. Then, invoke a move refactoring to move the variable declaration to class `D`. CodingSpectator will record the following descriptor for the performed refactoring.

```
<refactoring captured-by-codingspectator="true" code-snippet="&#x0A;public class D {&#x0A;&#x0A;&#x09;int a;&#x0A;&#x0A;}&#x0A;" comment="Move element &apos;&apos; to &apos;C.java&apos;&#x0A;- Original project: &apos;P&apos;&#x0A;- Destination element: &apos;C.java&apos;&#x0A;- Original element: &apos;D.a&apos;&#x0A;- Textual move only&#x0A;- Update references to refactored element" description="Move field" destination="/src&lt;{C.java" element1="/src&lt;{D.java[D^a" flags="589830" id="org.eclipse.jdt.ui.move" invoked-by-quickassist="false" invoked-through-structured-selection="true" members="1" navigation-history="{[Textual Move,BEGIN_REFACTORING,1305690979084],[MoveInputPage,OK,1305690981882],}" policy="org.eclipse.jdt.ui.moveMembers" selection-text="[int a [in D [in [Working copy] D.java [in &lt;default&gt; [in src [in P]]]]]]" stamp="1305690982783" status="&lt;OK&#x0A;&gt;" version="1.0"/>
```

There are two problems with the above descriptor.
1. `invoked-through-structured-selection="true"` instead of `invoked-through-structured-selection="false"`.
2. `selection-text="[int a [in D [in [Working copy] D.java [in &lt;default&gt; [in src [in P]]]]]]"` instead of `selection-text="a"`.

**Comment by vazexqi** [comment]
It seems that when you invoke it on the selection ("a"), the action method that is called is `org.eclipse.jdt.internal.ui.refactoring.reorg.ReorgMoveAction.run(IStructuredSelection)`. I confirmed this by setting a breakpoint there. Since this run(IStructuredSelection) is called, it is no wonder that the refactoring records it as such. This is the current setup of Eclipse

I am not sure how we can change this logic. The call stack is:

```
org.eclipse.jdt.ui.actions.MoveAction.run(ITextSelection) // This part is still using ITextSelection
|
org.eclipse.jdt.ui.actions.MoveAction.tryReorgMove() // This is where it gets converted to a structured selection
|
org.eclipse.jdt.internal.ui.refactoring.reorg.ReorgMoveAction.run(IStructuredSelection) // This action only has a run method for IStructuredSelection
```

If we want to change it then we would need to intercept it in the tryReorgMove() method and also create a run(ITextSelection) method for ReorgMoveAction.

**Comment by reprogrammer** [comment]
Tests move.(T23..T29) in 274cfc06a73015751e6733de028f0443db805422 fail because of this issue.
