### ISSUE TITLE
Add more content and menu items to the home page

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#228]
I suggest to make the following changes to the home page of CodingSpectator.
1. Add the following to the "General FAQ".
   - How can I exclude some of my projects from being tracked by CodingSpectator?
   - You should have two installations of Eclipse: one with CodingSpectator and the other one without CodingSpectator. If you don't want CodingSpectator to collect information about certain projects, you should use the installation of Eclipse without CodingSpectator to work on those projects.
2. Change the answer to the following question on the FAQ page:
   - Where does CodingSpectator store data?
   - CodingSpectator stores its data locally in your Eclipse workspace directory, under .metadata/.plugins/edu.illinois.codingspectator.data. And, it uploads this data to secure storage servers at the University of Illinois regularly.
3. Add a menu item called "Documentation" that provides links to the HTML and PDF versions of the user guide. This menu item makes it easier to access the user guide.
4. Add a menu item called "Contact Us" that just instructs the visitors to use the e-mail address codingspectator@cs.illinois.edu to reach us. The e-mail address is already listed at the bottom of every page of the web site. So, the visitor might have to scroll to the bottom of the page to see the contact address. Therefore, I suggest to add a dedicated menu item to make the e-mail address more accessible.

**Comment by vazexqi** [comment]
Done. I didn't make the changes for Item #4. It seems redundant.
- Our pages for each section is short so there is very little (or no) scrolling involved.
- We have a "People" page that is already pretty short and the contact us link is at the bottom.

**Comment by reprogrammer** [comment]
@vazexqi: Thanks for updating the homepage. I like the thumbnails you've added for the html and pdf versions of the user guide.
