### ISSUE TITLE
Postprocessing required for SVN operations

### ISSUE THREAD

**Issue by Wanderer777** [vazexqi/CodingSpectator#241]
I noticed that in one of the recorded operation sequences SVN update operations are recorded as an SVN commit operation followed (not necessary immediately) by an external change operation of the same file. We need to implement a postprocessor, which would replace the spurious SVN commit operation and the following external change operation with the corresponding SVN update operation in order to avoid counting spurious SVN operations in our data analysis.

**Comment by Wanderer777** [comment]
I could not reproduce this problem in any configuration I tried. Presumably, this happens only for a specific configuration/version of SVN client. So, in a case-by-case manner, some of the recorded operation sequences might require the above mentioned postprocessing.

**Comment by reprogrammer** [comment]
@Wanderer777: Does this problem exist in the latest version of CodingSpectator? We might be able to find out the SVN client that makes CodingTracker produce such data.

**Comment by Wanderer777** [comment]
@reprogrammer: I have no data for the latest version of CodingSpectator (as I could not reproduce the problem), but considering that this functionality was not changed for the latest version, I would assume that this problem still exists. As a starting point, it would be good if you could take a look at the setup used by participant cs-102, for whom CodingTracker recorded these spurious SVN commits.

**Comment by reprogrammer** [comment]
@Wanderer777: I noticed some SVN exceptions in the error log of cs-102. Do you think these exceptions are related to the spurious SVN commits CodingTracker has recorded?

**Comment by Wanderer777** [comment]
@reprogrammer: I think that these SVN exceptions demonstrate that there is something wrong with the SVN client and/or project setup of cs-102, and therefore, they could be related to the spurious SVN commits recording with a high probability. It is interesting that some of those exceptions complain about missing admin area (.svn folder) in the binary path (i.e. inside /bin folder), which looks as if the compiled classes are added to the version control repository.

**Comment by reprogrammer** [comment]
@Wanderer777: Please feel free to send an e-mail to participant cs-102 to get more information about his/her Subversion setup.

**Comment by reprogrammer** [comment]
@Wanderer777: Participant cs-102 has the following SVN plug-ins installed on his/her Eclipse.
-  Subclipse (Required) 1.6.17  org.tigris.subversion.subclipse.feature.group
-  Subclipse Integration for Mylyn 3.x (Optional)   3.0.0   org.tigris.subversion.subclipse.mylyn.feature.group
-  Subversion Client Adapter (Required) 1.6.12  org.tigris.subversion.clientadapter.feature.feature.group
-  Subversion JavaHL Native Library Adapter (Required)  1.6.15  org.tigris.subversion.clientadapter.javahl.feature.feature.group
-  Subversion Revision Graph    1.0.9   org.tigris.subversion.subclipse.graph.feature.feature.group
-  SVNKit Client Adapter (Not required) 1.6.15  org.tigris.subversion.clientadapter.svnkit.feature.feature.group
-  SVNKit Library   1.3.5.7406  org.tmatesoft.svnkit.feature.group

**Comment by Wanderer777** [comment]
@reprogrammer: Thank you for providing information about the setup of participant cs-102. Installing the above plugins (newer versions for some of them), I managed to reproduce the problem.

After an update operation, this SVN client (Subclipse) separately refreshes .svn folder and then, the folder that contains the source files. As a result, the first refresh is treated as a commit and the second is treated as an external modification (which is correct in some sense, since an update IS an external modification). It looks that postprocessing of these spurious commits is the easiest solution because we can spot sequences that have this anomaly (meaning that a participant used Subclipse) and transform commits followed by external changes into updates. 

At the same time, initial commits are more problematic as they are not followed by externally added files (they are not recorded in order to avoid recording all files of an application that is checked out). But recording externally added files (which are collected in the current version anyway, just not recorded) would allow postprocessing for spurious initial commits as well.  

The only drawback of postprocessing is that CodingTracker will capture more snapshots than needed since every commit or initial commit results in recording a snapshot of the underlying file. I am not sure how big this problem is. Maybe for a big application that is checked out (or updated for the majority of its files) this could explode the size of the record file. Therefore, I will think about a solution that would not require postprocessing (i.e. it would not record spurious commits or initial commits).

**Comment by Wanderer777** [comment]
It looks like capturing the correct update (or checkout) operations instead of spurious commits followed by external modifications (or spurious initial commits not followed by any additional operations) would require fundamental changes in the way CodingTracker tracks version control operations. And currently we do not have neither time nor resources for this.

Also, I found how spurious initial commits can be easily filtered out: we will just ignore initial commits of files that were never edited. This will filter out checkout operations erroneously recorded as initial commits. And in the case when a file is indeed initially committed but is never edited before this initial commit in presence of CodingSpectator (and thus, nothing is recorded for this file), filtering it out is still fine since for our purposes it looks like a checkout.

So, the only concern is that we will capture redundant snapshots. But this would not affect the correctness of the analyzed operation sequences, since the postprocessing step would fix the spurious commits and initial commits.

**Comment by reprogrammer** [comment]
@Wanderer777: Is it possible to automatically preprocess the log file when we'd like to parse it or we must do the preprocessing manually?

**Comment by Wanderer777** [comment]
The postprocessing of spurious version control operations should be done automatically since doing this manually would be too burdensome. Besides, automating this postprocessing does not look hard. The only manual involvement would be to detect that a particular sequence requires this postprocessing. This issue will reflect the work on automating this postprocessing step.
