### ISSUE TITLE
NumberFormatException in OperationLexer.readInt(...)

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#244]
When I tried to load this particular participant's data in CodingTracker replayer, I get the following dialog:

Wrong format. Could not load user operations from file: .../cs-103/27c4f8c1-2128-4aee-9766-28a70771cbea/1.0.0.201104162211/codingtracker/codechanges.txt

When I try to load it programmatically using `OperationDeserializer.getUserOperations(String)`, I noticed that we have a NumberFormatException for the first line in that file.

**Comment by Wanderer777** [comment]
Starting with the May 17th (internal) release of CodingSpectator, CodingTracker uses a new format for its record file, which is incompatible with the previous format. I implemented a format converter that would allow to update the older record files to the new format and planned to convert all old sequences at some point. If you like to do it yourself, please take a look at class `edu.illinois.codingtracker.tests.UpdateOperationSequenceFormat` - specify the path to the file you like to convert, set OLD_CODINGTRACKER_FORMAT environment variable, remove @Ignore annotation, and run this class as a JUnit plugin test.

**Comment by reprogrammer** [comment]
@Wanderer777: Are CodingTracker log files versioned? Is there a way to automatically detect that the format of a file is old? I'm asking this to see if it's possible to fix the CodingTracker log files automatically. In other words, can the deserializer detect that the log file is in an old format, update its format automatically and then parse its contents? Simply, I'm trying to see if there is a way to automate the invocation of `UpdateOperationSequenceFormat`.

**Comment by Wanderer777** [comment]
@reprogrammer: CodingTracker record files are versioned in a sense that they appear under a folder that represents a release date of CodingSpectator, but there is nothing inside the record file itself that says anything about its version. Besides, versioning is an overkill here, as there are just two formats: the old and the new, and I do not expect that the new format would be changed (though it could be extended in a backwards compatible manner). 

An automatic detection means that there is an operation that can not be deserialized correctly. If we assume that the only reason for this is the older format, then it can be adjusted on the fly, i.e. it would not require to unparse the recorded sequence in the new format, but rather would adjust to the old format completely transparently to a user. To achieve this, every operation, whose format has changed, should be able to detect that it tries to deserialize itself from the old format and adjust accordingly. This would make the use of `UpdateOperationSequenceFormat` unnecessary, and would completely stream line the transition from the old format to the new one. In general, it looks doable, but I need to check each operation, whose format has changed, to see if it can adjust automatically to the old format.

**Comment by reprogrammer** [comment]
@Wanderer777: We've started to analyze the data. Currently, I'm ignoring some of our older data because of the occasional problems with parsing CodingTracker logs. If you fix the logs, we'll have more data at our disposal. Could you please fix the old CodingTracker log files?

**Comment by Wanderer777** [comment]
@reprogrammer: Do we have a repository to store the fixed logs? It would help if you upload to this repository the old logs that require fixing such that I commit the fixed logs over them. Some logs might require more fixing than just the format, but lets first start with those with the old format, and later we will use the same repository for all postprocessing of CodingTracker logs.

**Comment by Wanderer777** [comment]
I updated all older sequences to the newer format and committed them to the internal repository.
