### ISSUE TITLE
Describe the data that CodingSpectator captures on the FAQ page

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#246]
I received the following in response to my invitation e-mail to a mailing list.

> it would be great if you could explain on the FAQ WHAT data you store. Do you extract function names, variable names, and stuff like that or e.g only which functions / commands in Eclipse are being used.
> 
> Do you calculate metrics about loc / class or / function and stuff like that.
> 
> Just need to get some details on that to see if its possible to use at work.

Let's add the following questions and answers to our FAQ page.

**What data does CodingSpectator capture from my workspace?**
CodingSpectator collects information about some of the commands that you invoke in the workbench. These commands correspond to edit actions and various wizards and dialogs in Eclipse that are designed to facilitate programming. CodingSpectator captures the arguments and steps taken to invoke these commands.

**Does CodingSpectator capture anything from my source code?**
Yes, CodingSpectator captures pieces of your source code. But, we store these pieces of source code at secure servers at University of Illinois, and never share them with others. Even when we publish the results of our study, we won't reveal the captured pieces of source code. Please refer to the privacy and confidentiality section of our [consent form](http://codingspectator.cs.illinois.edu/ConsentForm) for more information.

**Comment by vazexqi** [comment]
Addressed in our Subversion repository. See http://codingspectator.cs.illinois.edu/FAQ/index.html
