### ISSUE TITLE
Import the CSV file into a SQL database

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#254]
Import the collected data into a database to easily execute different queries.

**Comment by reprogrammer** [comment]
Currently, the program will throw an exception if the database is not cleaned up. We need to fix this problem. But, for the time being, you just need to delete HSQLDB files prior to running the program.

**Comment by vazexqi** [comment]
Given that our original data is in XML format, we would need to convert XML into a flat RDBMS. What was inadequate about using XQuery? Preserving the data in XML format also allows us to use it with Tableau. Tableau also supports RDBMS but only in the paid version.

**Comment by reprogrammer** [comment]
@rajkuma1 is good at writing SQL queries. So, he imported the CSV into an RDB and quickly wrote a few queries to find the answers to some of our research goals. We can still use XQuery if we find it better for writing certain queries.
