### ISSUE TITLE
Browsers don't show our favicon

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#264]
I opened the CodingSpectator homepage in Chrome and Firefox. But, none of them showed our favicon. Then, I tried http://illinois.edu, and only Firefox showed its favicon. It looks like at least Firefox should show our favicon.

**Comment by vazexqi** [comment]
Chrome shows it on the tab (it works on mine). It's not shown at the address bar. 

Firefox does not show the icon for codingspectator.cs.illinois.edu

**Comment by reprogrammer** [comment]
What is the problem? Why doesn't Firefox pick our favicon?

**Comment by reprogrammer** [comment]
Firefox shows the following problem when I open the URL http://codingspectator.cs.illinois.edu/favicon.ico.

> The image “http://codingspectator.cs.illinois.edu/favicon.ico” cannot be displayed because it contains errors.

**Comment by reprogrammer** [comment]
I replaced the favicon by the one from http://illinois.edu. This fixes the error message above. But, it doesn't make firefox show the favicon for HTML pages.

**Comment by reprogrammer** [comment]
This issue doesn't show up in the new homepage of CodingSpectator.
