### ISSUE TITLE
Does CodingTracker work fine with refresh on access in Indigo?

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#266]
Eclipse Indigo has added a new feature to refresh files upon access (See [Eclipse Indigo - New and Noteworthy](http://download.eclipse.org/eclipse/downloads/drops/R-3.7-201106131736/eclipse-news.html) and [Lightweight refresh on access](http://download.eclipse.org/eclipse/downloads/drops/R-3.7-201106131736/eclipse-news-part1.html)). I know that CodingTracker handles external edits. But, I don't know if this new feature is going to make any difference for CodingTracker. Anyways, I'd like to point out this feature so that @Wanderer777 makes sure that this new feature is not causing any troubles for CodingTracker.

**Comment by Wanderer777** [comment]
@reprogrammer: Thanks for pointing me to this new feature. I tried in Indigo "Refresh using native hooks or polling" and the new feature "Refresh on access" as well as disabling both of them (i.e. keeping only the manual refresh). CodingTracker worked fine in all scenarios. In general, all Eclipse refresh features can be simulated with manual refreshing at specific timing.
