### ISSUE TITLE
Instrument Inline Constant Refactoring

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#27]

**Comment by vazexqi** [comment]
Closed in c3916685b9a79a32d91a021b048744c254fd796b

However, notice that with this particular refactoring, the code snippet that we capture tends to be bigger than usual. The reason for this is that the refactoring is applied to a field.

Field tend to be regarded as "near" top-level things. In the current getCodeSnippet method, when we try to get the parent it will very quickly fetch the top-level class after a few iterations of getParent(). Therefore, we tend to capture the entire class text.

This might or might not be a problem but it is worth documenting in case we want to improve our getCodeSnippet heuristic.

**Comment by reprogrammer** [comment]
Captured a possible unavailable inline constant refactoring in 091c467b680319cf7862ce399cd6285f3645700e.

**Comment by reprogrammer** [comment]
cb963dae28ee2dfda953f254db79d5c446a21f34 captured unavailable inline constant refactorings in `InlineConstantRefactoring#checkInitialConditions`.
