### ISSUE TITLE
CodingTracker does not track code changes in conflict editors opened via Compare With menu

### ISSUE THREAD

**Issue by Wanderer777** [vazexqi/CodingSpectator#286]
If a conflict (compare) editor is opened via Compare With menu item of a file's context menu (i.e. menu that appears after right clicking on a file), then CodingTracker neither records that a conflict editor was opened, nor records any changes in this editor. Instead, when this conflict editor is saved (which is recorded correctly because this event is registered via a different mechanism), CodingTracker records an external change operation. This means that the operation sequence is not broken, because the content of the edited file will be recaptured on the subsequent modification, but the intermediate editing steps that happened in a conflict editor are lost.

**Comment by reprogrammer** [comment]
@Wanderer777: Do you know how long this bug has existed in CodingTracker? Which releases of Eclipse does it affect (Helios and/or Indigo)? Can the fix be postponed to the next release?

**Comment by Wanderer777** [comment]
@reprogrammer: I think this bug was there since the beginning. I never tried this kind of scenario, and thus, it was never supported in CodingTracker. It is a general scenario that affects both Helios and Indigo. The fix can be postponed to the next release, but I planned to investigate this issue today and in case it has an easy and quick solution, it probably can become part of the current release.

**Comment by Wanderer777** [comment]
CodingTracker now records code changes in conflict editors opened via Compare With menu, but to replay such sequences, a postprcessing step is required. For more details see issue #295.
