### ISSUE TITLE
Report verification activities after refactorings

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#293]
Report the probability that programmers verify their refactorings by running their programs or tests.

**Comment by reprogrammer** [comment]
@Wanderer777: 32d3555e96710ba69407ecbea1c2f3a804b18515 added a few accessors to some of the event classes of CodingTracker. Please review this commit and let me know if this change looks good to you.

**Comment by Wanderer777** [comment]
@reprogrammer: Your changes look good to me. If you like, you might consider using `isSuccess` instead of `getSuccess` name for the getter of a boolean flag.

**Comment by reprogrammer** [comment]
@Wanderer777: How about renaming the boolean flag from `success` to `successful` and the getter from `getSuccess` to `isSuccessful`?

**Comment by Wanderer777** [comment]
@reprogrammer: The same naming scheme is used in many other CodingTracker operations and it was actually borrowed from Eclipse classes, so I would prefer to keep `success`. But you can name the getter `isSuccessful` if you like.

**Comment by reprogrammer** [comment]
@Wanderer777: Let's keep the boolean flag `success` and rename `getSuccess` to `isSuccess`.
