### ISSUE TITLE
What is FinishedRefactoringOperation.success?

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#297]
@Wanderer777: What does the value of `FinishedRefactoringOperation.success` indicate. What refactorings does CodingTracker consider to have failed. Can you give some examples of how a refactoring could fail?

**Comment by Wanderer777** [comment]
@reprogrammer: `FinishedRefactoringOperation.success` indicates whether a refactoring failed or not. CodingTracker considers that failed refactorings are those, whose event type is `OperationHistoryEvent.OPERATION_NOT_OK` (please see details in `OperationHistoryListener#historyNotification(OperationHistoryEvent)`) - exactly the same condition is used by CodingSpectator when it detects whether a refactoring failed to decide whether it requires checking for compilation errors (please see `RefactoringProblemsListener#hasRefactoringFailed(OperationHistoryEvent)`).

For example, a rename compilation unit refactoring would fail if it could not successfully perform the required IO operations with the underlying file (e.g. the file is deleted during the refactoring).
