### ISSUE TITLE
Eliminate duplication of username in Submitter

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#3]
Right now Submitter has redundant information. It takes the username through its constructor but it also accesses the username through the preference store.

Resolution:

1) netid field in the preference page has to either removed or disabled since this information has to be set when the user is asked for authentication (through the Eclipse Secure Storage facility).

**Comment by reprogrammer** [comment]
See 30af3888125bf55d55c2f790d363c342f6c43e1b
