### ISSUE TITLE
Correct the timestamp of NewStartedRefactoringOperation when it is -1

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#301]
CodingTraker used to record the timestamps of refactorings incorrectly during a short period of time (See issue #237). As a consequence of this bug, the timestamp of `NewStartedRefactoringOperation` may be -1. Therefore, every client of CodingTracker that relies on the timestamp of `NewStartedRefactoringOperation` has to handle the incorrect timestamps. It would be nice if we could fix the problem once for all the clients of CodingTracker.

@Wanderer777: Given that the incorrect timestamps of `NewStartedRefactoringOperation` are not prevalent, will you be able to fix them manually?

**Comment by Wanderer777** [comment]
@reprogrammer: I think that for this kind of problem an automated postprocessing fixer should be easy to implement.
