### ISSUE TITLE
Submitter does not always notify others when it changes the watched folder

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#308]
`Submitter` notifies others when it's about to upload some data. Consequently, the data writers block the `Submitter` until they are done with their writes into the watched folder. This mechanism makes it possible to avoid conflicting accesses to the watched folder by the `Submitter` and data writers. However, the `Submitter` still writes to the watched folder without notifying the data writers. The method [Submitter#authenticateAndInitialize](https://github.com/vazexqi/CodingSpectator/blob/master/plug-ins/edu.illinois.codingspectator.monitor.ui/src/edu/illinois/codingspectator/monitor/ui/submission/Submitter.java#L58) performs `svn import` and `svn checkout` commands after authenticating the user, but it doesn't notify the data writers. Since issues #257 and #287 buffer the writes to the watched folder, the two SVN operations in [Submitter#authenticateAndInitialize](https://github.com/vazexqi/CodingSpectator/blob/master/plug-ins/edu.illinois.codingspectator.monitor.ui/src/edu/illinois/codingspectator/monitor/ui/submission/Submitter.java#L58) don't seem risky. But, I think it's safer to move all the SVN operations that manipulate the watched folder to the [`Submitter#submit`](https://github.com/vazexqi/CodingSpectator/blob/master/plug-ins/edu.illinois.codingspectator.monitor.ui/src/edu/illinois/codingspectator/monitor/ui/submission/Submitter.java#L96) method to ensure that the data writers get notified about all SVN operations.

**Comment by reprogrammer** [comment]
@Wanderer777: I think this issue shows an advantage of buffering the writes to the watched folder (issues #257 and #287). In general, buffering the writes to the watched folder seems to make our system more robust. What do you think?

**Comment by Wanderer777** [comment]
@reprogrammer: I think that as long as buffering the writes to the watched directory makes CodingSpectator more robust, we can keep it. We still do not have a complete solution to the problem of SVN conflicts, so we might change the way it works now. After we solve this problem, we can think again whether we need to keep buffering the writes into the watched directory.
