### ISSUE TITLE
Compute a measure of participants' use of CodingSpectator

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#316]
It would be nice to have the script [summarize-user-activities.rb](https://github.com/vazexqi/CodingSpectator/blob/master/scripts/summarize-user-activities.rb) report a rough estimate of how much code each participant has developed under the presence of CodingSpectator. I think it would be good enough to compute the total size of the CodingTracker logs of each participant. Even though this metric is very imprecise, it is good enough to give us a rough idea of how actively each participant has used CodingSpectator.

**Comment by Wanderer777** [comment]
@reprogrammer: I think that still imprecise but somewhat more objective measure would be to count the total number of operations recorded for each participant. After parsing a participant's data, this can be obtained as the size of the operation sequence list.

**Comment by reprogrammer** [comment]
@Wanderer777: We'll use this imprecise but quick method to continuously monitor the activities of our participants not for reporting statistics in our publications. A more precise approach is discussed in issue #321.
