### ISSUE TITLE
Mark the selection in the captured code snippet

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#317]
Sometimes refactorings are unavailable or report problems due to wrong selections. Therefore, it's interesting to study the selections. CodingSpectator captures both structural and textual selections (See issues #163 and #170). It stores the offsets of the textual selections relative to the captured code snippet. I suggest that we change the CSV file generator to add a column that contains the string corresponding to the offsets of the textual selections relative to the captured code snippet.

**Comment by vazexqi** [comment]
I'm using the selection column in #312. Is that different? What does the selection column report then?

**Comment by reprogrammer** [comment]
I had forgot the "selection-text" attribute. Thanks for reminding me. The "selection-text" attribute computes the string of the selection. However, the length of the selection is usually zero because most of the time the user just needs to place the cursor inside the right program element. The beginning offset of the attribute "selection-in-code-snippet" would help us determine the cursor position when the selection is empty. What is the best way to present where the user has placed the cursor?

**Comment by reprogrammer** [comment]
I think it would be nice to make the generator of the final CSV file add a column that contains the code snippets and their containing selections.
