### ISSUE TITLE
Investigate possible duplicates in recorded events

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#319]
In one participant (cs-107) we noticed that we have captured identical events numerous times in the event stream. In this particular case, we noticed several invocations of a PERFORMED change method signature captured through Eclipse. This is problematic because it leads to double (or even triple, etc) counting.

The nature of the problem seems to be that we capture the same refactorings in different version of CodingSpectator i.e. once in version x and once more in a later version, y. This could indicate that the problem occurs because of the way we are copying the data.

**Comment by reprogrammer** [comment]
CodingSpectator copies the refactoring histories captured by Eclipse into the versioned watched folder. If the user has used several versions of CodingSpectator, there's a possibility of capturing same refactoring logs under different version folders. As long as we take this duplication into account while analyzing the captured data, there will be no problem.
