### ISSUE TITLE
Instrument Introduce Parameter Object Refactoring

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#32]

**Comment by vazexqi** [comment]
It appears that this is going to be a compound refactoring. It will rely on the "Change Method Signature Refactoring" to change all call sites of this method so that it uses the new ParameterObject. See org.eclipse.jdt.internal.corext.refactoring.code.IntroduceParameterRefactoring.getRefactoringDescriptor()

We might want to make a smart decision here in the interest of time. I don't foresee this refactoring being used much. So we might be OK capturing only just a _bit_ of information instead of the entire refactoring description.

**Comment by vazexqi** [comment]
Introduce Parameter appears to be a pretty popular refactoring according to http://portal.acm.org/citation.cfm?id=1555001.1555044. We have instrumented most of the top refactorings in that list and we should instrument this one as well (soon) for completeness.

Personally, I haven't used this refactoring much but the statistics seems to show that Toolsmiths and Users use it a lot.

**Comment by reprogrammer** [comment]
Test `changemethodsingnature.T01` revealed that CodingSpectator doesn't record the fact that the refactoring has been invoked from the package explorer view. Also, this test fails because it cannot parse the expected CodingSpectator descriptor.
