### ISSUE TITLE
Estimate the number of hours of using CodingSpectator

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#321]
It would be nice to report the number of hours that our data covers. Is it possible to analyze CodinTracker logs to estimate the number of hours that every participant has programmed under the presence of CodingSpectator?

**Comment by reprogrammer** [comment]
@Wanderer777, @vazexqi: We can also consider the UDC data to estimate the number of hours of development.

**Comment by reprogrammer** [comment]
@Wanderer777: Thanks for providing `UsageTimeAnalyzer`. How can we use this analyzer?

**Comment by Wanderer777** [comment]
@reprogrammer: You can use `UsageTimeAnalyzer` exactly the same way as you use `RefactoringIntensityAnalyzer`, i.e. specify the root folder and then run it as a JUnit Plugin Test. The combined result will appear in the specified root folder, the file's default name is `combined.usage_time`.

**Comment by reprogrammer** [comment]
@vazexqi, @Wanderer777: I suggest that we change the name of the column `USAGE_TIME` to `USAGE_TIME_IN_MILLI_SECS` to make the unit of measurement clear.

**Comment by reprogrammer** [comment]
@Wanderer777: I renamed `USAGE_TIME` to `USAGE_TIME_IN_MILLI_SECS` in the SQL script (See commit f2e39ec9d66dd8920d8869b98776d8924b89256e). I think you also need to update the column name of the CSV file that your analyzer generates accordingly.

**Comment by Wanderer777** [comment]
@reprogrammer: The column name in the CSV file generated by the analyzer is 'usage time (ms)'. And as far as I can remember, this column always had this name. So, it never matched the SQL script name. Therefore, I am not sure why we need to match it now (its current name looks sufficiently descriptive to me).
