### ISSUE TITLE
CodingSpectator does not install on Eclipse Indigo SR1

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#328]
Eclipse Indigo SR1 refuses to install CodingSpectator v1.0.0.201107172337 by reporting the following the error message:

<pre>
Cannot complete the install because of a conflicting dependency.
  Software being installed: CodingSpectator 1.0.0.201107172337 (edu.illinois.codingspectator.feature.group 1.0.0.201107172337)
  Software currently installed: Eclipse for RCP and RAP Developers 1.4.1.20110909-1818 (epp.package.rcp 1.4.1.20110909-1818)
  Only one of the following can be installed at once: 
    Java Development Tools Core 3.7.0.201107172337 (org.eclipse.jdt.core 3.7.0.201107172337)
    Java Development Tools Core 3.7.1.v_B76_R37x (org.eclipse.jdt.core 3.7.1.v_B76_R37x)
  Cannot satisfy dependency:
    From: CodingSpectator 1.0.0.201107172337 (edu.illinois.codingspectator.feature.group 1.0.0.201107172337)
    To: edu.illinois.codingspectator.jdt.patch.feature.group [1.0.0.201107172337]
  Cannot satisfy dependency:
    From: Eclipse for RCP and RAP Developers 1.4.1.20110909-1818 (epp.package.rcp 1.4.1.20110909-1818)
    To: org.eclipse.epp.package.rcp.feature.feature.group [1.4.1.20110909-1818]
  Cannot satisfy dependency:
    From: EPP RCP/RAP Feature 1.4.1.20110909-1818 (org.eclipse.epp.package.rcp.feature.feature.group 1.4.1.20110909-1818)
    To: org.eclipse.jdt.feature.group 3.7.0
  Cannot satisfy dependency:
    From: EPP RCP/RAP Feature 1.4.1.20110909-1818 (org.eclipse.epp.package.rcp.feature.feature.group 1.4.1.20110909-1818)
    To: org.eclipse.pde.feature.group 3.7.0
  Cannot satisfy dependency:
    From: API Tools 1.0.301.v20110728_r371 (org.eclipse.pde.api.tools 1.0.301.v20110728_r371)
    To: bundle org.eclipse.jdt.core [3.7.1,4.0.0)
  Cannot satisfy dependency:
    From: Eclipse Plug-in Development Environment 3.7.1.r37x_v20110810-0800-7b7qFVtFEx2XnmZ4jlM5mjM (org.eclipse.pde.feature.group 3.7.1.r37x_v20110810-0800-7b7qFVtFEx2XnmZ4jlM5mjM)
    To: org.eclipse.pde.api.tools [1.0.301.v20110728_r371]
  Cannot satisfy dependency:
    From Patch: edu.illinois.codingspectator.jdt.patch.feature.group 1.0.0.201107172337 Eclipse Java Development Tools 3.7.1.r371_v20110810-0800-7z8gFcoFMLfTabvKsR5Qm9rBGEBK (org.eclipse.jdt.feature.group 3.7.1.r371_v20110810-0800-7z8gFcoFMLfTabvKsR5Qm9rBGEBK)
    To: org.eclipse.jdt.core [3.7.0.201107172337]
</pre>

**Comment by reprogrammer** [comment]
The fix for issue #327 resolved this issue as well.

**Comment by Bananeweizen** [comment]
Can't you just use [3.7.0, 4.0.0) as dependency to run in 3.7.0 and 3.7.1 as well? Promoting this research study in blogs is of no help if people can't even install the plugin...

http://wiki.eclipse.org/Version_Numbering#How_to_specify_plug-in_requirements

**Comment by reprogrammer** [comment]
@Bananeweizen

Thanks for your interest in the CodingSpectator study. To build CodingSpectator, we have changed the source code of Eclipse. Currently, CodingSpectator is not binary compatible with Eclipse 3.7.1 (See issue #330). Therefore, we need to create another version of CodingSpectator for Eclipse 3.7.1. Because of the overhead of supporting new versions of Eclipse, CodingSpectator doesn't currently support the latest release of Eclipse. We'll notify you when CodingSpectator supports Eclipse 3.7.1.

**Comment by reprogrammer** [comment]
Issue #338 has resolved this issue.
