### ISSUE TITLE
Investigate repeated detections of inconsistencies between local and remote data

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#333]
Recently, CodingSpectator has detected inconsistencies between the  local and remote data of participant cs-106 repeatedly. This phenomenon is suspicious because this participant didn't have any problems submitting data in the past. Therefore, I suggest that we investigate the root cause of this behavior of CodingSpectator for this particular participant.

**Comment by reprogrammer** [comment]
@Wanderer777: Participant cs-121 told me today that he or she had noticed long running upload jobs of CodingSpectator and cancelled a couple of them. Other participants have probably noticed the long running jobs due to the frequent deletions of remote data. We need to fix this issue as soon as possible.

**Comment by reprogrammer** [comment]
@Wanderer777: I suspect that CodingSpectator detects too many inconsistencies because of wrong revision numbers. CodingSpectator may be relying on a global revision number that gets updated by anyone's commit. I realized that we didn't test the submission mechanism of CodingSpectator when multiple participants interleave their submissions. I'm going to try out this scenario and update this issue shortly.

**Comment by reprogrammer** [comment]
@Wanderer777: I just tested a scenario where the submissions of two users are interleaved and confirmed that CodingSpectator gets confused and deletes the remote data unnecessarily. My next step is to write an automated test to cover this scenario.

**Comment by Wanderer777** [comment]
@reprogrammer: This is a really unfortunate bug since all participants are severely affected. I agree that it should be fixed ASAP. To establish versions mismatch, CodingSpectator should check an entity, whose revision number is not updated globally, i.e. it is updated only by the commits of this particular participant.

**Comment by reprogrammer** [comment]
@Wanderer777: Commits c4dcbb2 .. a439453 added an automated test to reveal the bug reported in this issue. Next, I'll fix the bug such that the test passes.

**Comment by reprogrammer** [comment]
@Wanderer777: Commit a6b1769 fixed this issue. The next step is to release a new version of CodingSpectator that includes this fix (See issue #334).
