### ISSUE TITLE
Reorganize the plug-ins folder

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#339]
I plan to move the plug-ins that are directly inside the "plug-ins" folder to "plug-ins/common". This change will lead to the following cleaner organization of our plug-ins folder:

<pre>
plug-ins
  common
  helios
  indigo
  indigo-sr1
</pre>

If you have other suggestions for the name of the new folder, which is currently going to be "common", please let me know. I was considering names like "eclipse-independent" and "release-independent" but found them to be too long.

Once I move some of the plug-ins inside our repository, you'll have to reimport them into your Eclipse workspaces from their new paths.

**Comment by reprogrammer** [comment]
@Wanderer777: Does CodingTracker have changes that haven't been merged into master yet? If so, it might be better to reorganize the plug-ins folder after you merge your changes.

**Comment by Wanderer777** [comment]
@reprogrammer: There are two active branches for CodingTracker - `codingtracker` and `codingtracker-ast-inference`. The latter should never be merged into `codingtracker` or `master`. The former contains only changes related to replaying since its last merging with `master`, so merging it back to `master` is not critical for the coming release, but we can do it just for a better maintenance. What do you think?

**Comment by reprogrammer** [comment]
@Wanderer777: In general you would have an easier time if you merge your work into master more frequently. So, I encourage you to merge the `codingtracker` branch into `master` as soon as possible. Could you please remind me why the branch `codingtracker-ast-inference` should be never merged into `master`?

**Comment by Wanderer777** [comment]
@reprogrammer: OK, I merged `codingtracker` in `master`. At the moment, we can not safely mix recording of raw evolution data and inferring AST node operations, therefore `codingtracker-ast-inference` should not get into the release.

**Comment by reprogrammer** [comment]
@Wanderer777: Does that imply that `codingtracker-ast-inference` is a [feature branch](http://martinfowler.com/bliki/FeatureBranch.html)? Does it make sense to use [feature toggle](http://martinfowler.com/bliki/FeatureToggle.html) to merge it back to `master`?

**Comment by Wanderer777** [comment]
@reprogrammer: I do not see any reason to merge `codingtracker-ast-inference` into `master`, since I doubt we will need to release its functionality to our participants in future. Anyway, I regularly merge `master` into it (through `codingtracker`), so there would not be a problem to merge it into `master` later, if we decide so.

**Comment by reprogrammer** [comment]
@Wanderer777: I got some conflicts in CodingTracker plug-ins when I tried to merge `master` into `indigo-sr1`. Would you please merge `master` into `indigo-sr1`?

**Comment by Wanderer777** [comment]
@reprogrammer: Done.

**Comment by reprogrammer** [comment]
I got the following error when trying to move a few plug-ins to "common/" and commit:

<pre>
Error: Attempting to commit a file that is longer than 200 characters.

plug-ins/common/edu.illinois.codingspectator.logstocsv.tests/resources/04/input/cs-000/00000000-0000-0000-0000-000000000000/1.0.0.qualifier/eclipse-refactorings/Prj/2011/8/33/.svn/text-base/refactorings.history.svn-base
has 219 characters.
</pre>


See [my tweet](http://twitter.com/#!/MohsenVakilian/status/150052466510143488).

@Wanderer777: Do you think a path of length 219 will cause troubles for you? How about increasing our path limit to 220 characters?

**Comment by Wanderer777** [comment]
@reprogrammer: A path limit of 220 leaves just 35 characters for the root of CodingSpectator. As far as I can see, it should not cause a problem for my current setup, but it is really close, and would reduce the flexibility of placing the root folder considerably. So, I wonder if it is really needed to use such long paths in tests. Also, I noticed that the limit is exceeded by 19 characters while the length of the word "common" is 6 (including slash - 7), so it looks like the limit was already exceeded before your last change or there was another change besides adding "common" path fragment.

**Comment by reprogrammer** [comment]
@Wanderer777: I'll reduce the length of the workspace ID to fit the path in 200 characters.

**Comment by reprogrammer** [comment]
@Wanderer777: I used the command `find plug-ins/edu* -iname "*" | awk '{ print length(),$0 | "sort -nr" }' | head -200` to find the [list](https://docs.google.com/spreadsheet/ccc?key=0AheYLxbSgV2udElCTjBHenB5cmF4Q1RZanRlcDU1Vmc) of 200 longest paths that match the pattern `plug-ins/edu*` in our repository.

Looking at our longest paths, it should be sufficient to shorten the length of the workspace ID in `edu.illinois.codingspectator.logstocsv.tests` and `edu.illinois.codingspectator.mergehistories.tests`.

**Comment by reprogrammer** [comment]
@Wanderer777 

b499e17a35085af72e60b5634ae82d02c02f5118 moved some of the plug-ins to "plug-ins/common". Please update your workspaces accordingly.
