### ISSUE TITLE
Externalize the strings with URLs and authentication messages

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#345]
Externalize the strings that contain the URLs to the subversion repository or the message on the authentication dialog. This would make it possible to change these strings without building CodingSpectator from source.

**Comment by reprogrammer** [comment]
Externalize the branding information so that others can rebrand CodingSpectator easily.

**Comment by vazexqi** [comment]
@reprogrammer : Did you find someone who is interested in reusing the infrastructure?

**Comment by reprogrammer** [comment]
I'm making the infrastructure more reusable and going to explain it in my thesis. Hopefully, this would make it easier for others to reuse.
