### ISSUE TITLE
Setup a GitHub static page to point to the update site

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#35]
See http://pages.github.com/ for details.

**Comment by reprogrammer** [comment]
We created the static page based on the repository at http://github.com/eclipsewatcher/eclipsewatcher.github.com

**Comment by vazexqi** [comment]
I'm reopening this since it is technically done yet. We know the mechanism for doing it but we haven't released it yet.

**Comment by vazexqi** [comment]
We have our page at http://codingspectator.github.com/updates

**Comment by reprogrammer** [comment]
Our illinois address is http://codingspectator.cs.illinois.edu/.

**Comment by vazexqi** [comment]
I've tested it in Eclipse and it redirects properly.
