### ISSUE TITLE
Make the patch applicable to a wide range of releases of Eclipse Helios

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#40]
Right now, our feature patches target specific versions of JDT and LTK on the target platform. Therefore, these patches are very brittle. Andrew Niefer propose [a solution](http://aniefer.blogspot.com/2009/06/patching-features-part-2.html) that requires a manual change to one of the generated metadata files. Specifically, he suggests to replace the exact target version by a range of versions in the XML file contained in the `content.jar` of the update site project.

**Comment by vazexqi** [comment]
The problem with the above solution is that it is _manual_. The content.jar file is overwritten when you regenerate the patch.

The alternative (and it only works for our particular situation) is to create separate patches for each version. For the duration of our project, we might only have to deal with 2 release of Helios.

**Comment by reprogrammer** [comment]
Resolved by 8be0ac5dc2c8511dee23f3ea9598fb16d5ae2048.
