### ISSUE TITLE
Associate the version of the installed watcher plugin to its collected data.

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#42]
Every version of our plug-in might record different events. So, we need to tell the version of our plug-in using which the events have been captured.

One way to associate the version number to the collected data is to store the version number as part of the collected data. This results in some duplication as we have to record this information whether or not the user has upgraded his/her plug-in. Besides, it makes it harder for us to distinguish the data collected by different versions of our plug-in, as we have to examine the version number encoded in every version of the collected data to find out when it changes.

A better way to keep track of the version of the plug-in used to log the events is to reorganize the directory structure as one of the following.
1. `<RepositoryLocation>/<User>/<Workspace ID>/<Watcher Version>`
2. `<RepositoryLocation>/<User>/<Watcher Version>/<Workspace ID>`
3. `<RepositoryLocation>/<Watcher Version>/<User>/<Workspace ID>`

The above list of directory structures is not extensive. But, I kind of prefer the first directory structure, because it matches the ownership relationships. That is, a user has multiple workspaces, and every workspace gets monitored by different versions of our plug-in during a period of time. Moreover, it sorts the directories based on their lifetime. That is, users usually keep using a workspace longer than a specific version of our plug-in. This property limits the scope of changes to inner most directories.

**Comment by reprogrammer** [comment]
Resolved partially by fe094f2b58f64be448dd52a64a6dff0e5a388409.

**Comment by reprogrammer** [comment]
I'm reopening this issue because we need to recreate the SVN working directory when the user updates his plug-in. Updating the plug-in changes the URL associated to the SVN working directory. The main issue is how to make sure that the data collected during during the old version of plug-in don't get lost. There are two approaches to address this issue. One is to force the user to upload when he tries to update his plug-in. And, the other is keep the old SVN working directory besides the new one and upload it the first time uploads after updating his plug-in. The former is easier to implement but may damage the user experience. The latter is harder to implement.

**Comment by vazexqi** [comment]
There is another approach based on using the SVN tag feature. We can also try exploring that option.

**Comment by vazexqi** [comment]
We solved this issue _trivially_ by prepending the version number to the directory used to store the performed and canceled refactorings e.g. 3.6.1_refactorings.canceled.

Resolved in 68554c26bcffe4535ca6c130076456f1eefa8f65

**Comment by vazexqi** [comment]
Since we are storing the version number locally do we still need to store the version number in the repository URL? This change was introduced in fe094f2b58f64be448dd52a64a6dff0e5a388409

**Comment by reprogrammer** [comment]
Is it possible to dedicate a directory to each version rather than prepending the version number to `refactorings.canceled` and `refactorings.performed` directories? In other words, is it possible to put the canceled refactorings in `3.6.1/refactorings/canceled` instead of `3.6.1_refactorings.canceled`?

**Comment by vazexqi** [comment]
Yes it is. And the fix turns out to be easier than I thought it would be.

See c9848ac63098f1140930759237dcff696500a82c

**Comment by vazexqi** [comment]
What about storing the version number in the URL? Is that now redundant?

**Comment by reprogrammer** [comment]
Yes, we no longer need to explicitly add the version number to the URL.

**Comment by vazexqi** [comment]
Can you go ahead and revert those changes? We can still keep URLManager but we don't need to specify the version anymore.

**Comment by reprogrammer** [comment]
Removed the version number from the SVN URL in 708a5bf87924b79d6b60e0ab616c9d2aa95f85b0.
