### ISSUE TITLE
Repeatedly ask for authentication information until a valid one is provided.

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#45]
If we popup the username/password dialog and the user provides the wrong information or cancels it, we show the dialog again. But, if the user checks the save password option, he'll be shown a second dialog box to provide a master password. If the user cancels the second dialog, we no longer ask him for entering authentication information and no such information we'll be saved either.

**Comment by reprogrammer** [comment]
Resolved in 8dd3542cd7bf21c2caee3ced444137dd23400eda by throwing the proper exceptions when the secure storage doesn't complete and clearing the secure storage properly.

**Comment by reprogrammer** [comment]
This may not be an appropriate mechanism to get authentication information. It isn't critical for us to upload the data right away. If the user enters the wrong authentication information, it's reasonable to prompt him again. But, if he cancels the dialog, I think we shouldn't just postpone the data upload to the next startup of Eclipse.

**Comment by vazexqi** [comment]
This was resolved but I can't remember in which revision.
