### ISSUE TITLE
Don't ask for authentication information a lot.

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#46]
Currently, we upload the data every time Eclipse starts up. As a result, we ask for users username/password or master password every time the Eclipse starts up. This could quickly become annoying. We need to ask for authentication information less frequently. For example, we could set a policy to upload data at most once a day or on every nth startup of Eclipse.

**Comment by vazexqi** [comment]
Take a look at http://codingspectator.cs.illinois.edu/resources/installation/user-guide.html#FigSecureStoragePrompt

It seems that on Mac there is the option for always allow that should remember the password permanently. So this might alleviate the username/password problem.

**Comment by reprogrammer** [comment]
Resolved by 3ce0e4b948b879eb589a81e4f39259145476fdf5.

**Comment by vazexqi** [comment]
I am going to reopen this so that we can actually allow the user to cancel the operation as we discussed earlier. Not allowing the user to cancel the operation seems to go against the UI guidelines and might cause annoyance and frustration.

**Comment by vazexqi** [comment]
Resolved in dde85ea27ab7282aafffa9aa96e880a0fd6eb352
