### ISSUE TITLE
Error on initial upload on a clean workspace

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#47]
This bug is present in 6d3ef3afb4edec3cca41acaf4685c1ce3816ff9a

When the user first starts up the workspace, our Eclipse Watcher uploader kicks in and tries to upload something. However, since this is the first time that we are doing it, it seems that the UUID is null.

Therefore, on the initial commit and checkout, Eclipse Watcher actually pulls whatever is from http://subversion.assembla.com/svn/ganje/Experiment/nchen/ instead of http://subversion.assembla.com/svn/ganje/Experiment/nchen/<unique_UUID> since no UUID has been generated.

Suggested resolution: check why isn't UUID is null?

**Comment by reprogrammer** [comment]
The commit 8dd3542cd7bf21c2caee3ced444137dd23400eda resolves this issue by lazily generating the UUID.
