### ISSUE TITLE
Test to see if we handle all the different scenarios of the CodingSpectator prompter

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#53]
We need to test this very carefully since it is based on user interaction so there are lots of possibilities. I suggest testing for the following scenarios:

[Need to test when there is no network connection also]

0) Clean startup; user cancels the Eclipse Watcher prompt.
1) Clean startup; user enters username/password; doesn't save them.
2) Clean startup; user enters username/password wrongly; doesn't save them.
3) Clean startup; user enters username/password; saves them.
4) Clean startup; user enters username/password wrongly; saves them.

For scenarios 3 and 4 above, we should also check what happens if the user:
1) enters the master password wrongly
2) cancels on the dialog box

I am assuming that by the current logic, the plug-in will prompt the user until the right password is given.

**Comment by vazexqi** [comment]
0) Clean startup; user cancels the Eclipse Watcher prompt.

[With network][Without network]: It doesn't allow the user to cancel at all. Is this behavior acceptable?

2) Clean startup; user enters username/password wrongly; doesn't save them.

[With network] It displays the prompt again but doesn't inform the user that the username/password is wrong. It will keep prompting until a valid one is entered.

**Comment by reprogrammer** [comment]
I think this issue should be converted to a wiki page describing how to systematically test CodingSpectator.
