### ISSUE TITLE
Handle case where two people are pair programming and the svn working copy is already associated with one of them

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#54]
The working svn directory that we create for the user is associated with a URL that contains the username. So, when we the user changes the username, we have to recreate the working directory. We can do it by first doing an `svn export` to keep the existing data. This feature is not of a high priority because our users won't typically use multiple usernames unless they are pair programming  on a shared computer.

**Comment by vazexqi** [comment]
Good catch. This might not be a functional issue but since the participants might actually be required to pair program, we need to be sure to identify data from those who pair program and who program individually.

This is just a control step for our experiment.

**Comment by vazexqi** [comment]
We are going to present the username associated with the current SVN working copy. This field will not be editable.

**Comment by vazexqi** [comment]
Resolved in f126b917ff43d26cfcc0114311085de87478b9e6
