### ISSUE TITLE
Test that the update works correctly.

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#59]
Our feature has a couple of complexities.
1. It's composite feature that includes several feature patches.
2. Our feature two types of feature patches for Helios and Helios SR1.

Therefore, we need to make sure that the update mechanism works smoothly.

**Comment by reprogrammer** [comment]
Resolved by 45e90c5d0de5f5f7d30c1ef07e8fb5d6689d8dd2.

**Comment by vazexqi** [comment]
Here are the steps that I performed to verify this:
1. Generate plug-in and update-site and install into a clean installation of Eclipse.
2. This version of the plugin log changes in the folder .cancel
3. Merge feature from submit-log branch. This branch has more features that we want to test.
4. Regenerate the plug-ins and update-site. The update-site at this point contains two versions of the plug-in. The old and the new.
5. In Eclipse, select Help > Check for updates...
6. It detected that Eclipse Watcher needs to be updated.
7. Installed update and restarted.
8. The new features are indeed installed correctly.
