### ISSUE TITLE
Make only a single feature visible to the user through the update site

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#60]
We've compose several features into one. So, if the "Group items by category" in the "Install New Software..." dialog is selected, the user sees only the top level feature. Otherwise, he will see all the features including all the feature patches. Showing the individual features is not desirable because the  user might inadvertently miss some features that are required for our feature to work correctly.

**Comment by vazexqi** [comment]
Is this a _fixable_ issue? I assume that it is a direct result of checking that option. We can't prevent the user from checking/unchecking that button.

**Comment by reprogrammer** [comment]
I haven't found any solution so far. So, I've marked this issue as `Wontfix` and closed it.
