### ISSUE TITLE
Uninstall cleanly

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#61]
Uninstalling our plugin from within Eclipse deactivates the plugin in Eclipse. But, it doesn't remove the plugin and feature files from the Eclipse installation directory.

**Comment by vazexqi** [comment]
This might be because of the way that Eclipse works now. It allows you to "_rollback_" what you did (if you install/uninstall) so it probably keeps copies of the installed plug-ins around.

**Comment by vazexqi** [comment]
I can verify that it does not uninstall the plug-ins from the features folder even though the plug-in itself is no longer active in the current Eclipse installation.

I'm not sure how this affects things but we should keep a tab on this particular issue.

**Comment by reprogrammer** [comment]
Can we remove the watched directory when we uninstall CodingSpectator?

**Comment by vazexqi** [comment]
Check out [this FAQ](http://wiki.eclipse.org/FAQ_How_do_I_remove_a_plug-in%3F) about uninstalling. It confirms what I said about Eclipse only deactivating stuff and not fully uninstalling it.

I am still not able to find if there is a way to hook into the uninstallation process and delete data from the .metadata folder. By the way, we can't just delete the watched directory right? The .refactorings that LTK collects is also inside there. If we want to delete it we need to only delete our stuff.
