### ISSUE TITLE
Investigate if it is feasible to store the performed/canceled refactorings in our own plug-in directory

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#62]
It would be nice to be able to store the captured refactorings inside our own plug-in directory i.e. .WORKSPACE/.metadata/.plugin/edu.illinois.codingspectator.monitor/<data>

**Comment by reprogrammer** [comment]
We decided to keep the watched directory in the LTK directory. This choice frees us from worrying about moving the `.refactorings` folder into the watched directory.
