### ISSUE TITLE
How to get the version number of our plug-in?

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#63]
Right now in RefactoringWatcherTest.java and RefactoringHistorySerializer.java we have a line that says:

`Platform.getBundle("edu.illinois.codingspectator.monitor");`

We can't always expect that the plug-in edu.illinois.codingspectator.monitor to be present (sometimes it is not in the test). And we don't want to make a strong dependency between the LTK plug-in and our bundle.

What is the _best_ way to get a version number reliably for the purpose of versioning the data we collect?

**Comment by reprogrammer** [comment]
One option is to store the version in the preferences store. Using this method requires that we make sure the version gets stored in the preferences before any lookup happens.

**Comment by reprogrammer** [comment]
Stas has already made a dependency from `org.eclipse.jdt.ui` to `edu.illinois.codingspectator.codingtracker`. Therefore, I think it now makes sense to introduce a thin plugin called `edu.illinois.codingspectator.properties` that stores all the global properties. Then, we'll make any plugin that needs any of the global properties dependent on `edu.illinois.codingspectator.properties`.

**Comment by reprogrammer** [comment]
8565174282747ba87f5e0d2f0954857aa4481f3f added `getCodingSpectatorVersion` to `CodingSpectatorDataPlugin`.

**Comment by reprogrammer** [comment]
a6216b47ae6e85c0aa1a10d9230ef5b35c502966 got the version number from `CodingSpectatorDataPlugin` whenever this information is needed.
