### ISSUE TITLE
Installation fails due to an LTK version mismatch

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#66]
Stas reported the following error when trying to install our feature on his Eclipse.

<pre>
Cannot complete the install because of a conflicting dependency.
 Software being installed: Coding Spectator 1.0.0.201010071957 (edu.illinois.codingspectator.feature.feature.group 1.0.0.201010071957)
 Software currently installed: Eclipse for RCP and RAP Developers 1.3.0.20100609-1425 (epp.package.rcp 1.3.0.20100609-1425)
 Only one of the following can be installed at once:
   Refactoring UI 3.9.0.201010071957 (org.eclipse.ltk.ui.refactoring 3.9.0.201010071957)
   Refactoring UI 3.5.0.v20100526-0800 (org.eclipse.ltk.ui.refactoring 3.5.0.v20100526-0800)
 Cannot satisfy dependency:
   From: Coding Spectator 1.0.0.201010071957 (edu.illinois.codingspectator.feature.feature.group 1.0.0.201010071957)
   To: edu.illinois.codingspectator.monitor [1.0.0.201010071957]
 Cannot satisfy dependency:
   From: CodingSpectator 1.0.0.201010071957 (edu.illinois.codingspectator.monitor 1.0.0.201010071957)
   To: bundle org.eclipse.ltk.ui.refactoring 3.9.0
 Cannot satisfy dependency:
   From: Eclipse for RCP and RAP Developers 1.3.0.20100609-1425 (epp.package.rcp 1.3.0.20100609-1425)
   To: org.eclipse.epp.package.rcp.feature.feature.group [1.3.0.20100609-1425]
 Cannot satisfy dependency:
   From: EPP RCP/RAP Feature 1.3.0.20100609-1425 (org.eclipse.epp.package.rcp.feature.feature.group 1.3.0.20100609-1425)
   To: org.eclipse.platform.feature.group [3.6.0.v20100602-9gF78GpqFt6trOGhL5t0nJy5fyGHKrwNY]
 Cannot satisfy dependency:
   From: Eclipse Platform 3.6.0.v20100602-9gF78GpqFt6trOGhL5t0nJy5fyGHKrwNY (org.eclipse.platform.feature.group 3.6.0.v20100602-9gF78GpqFt6trOGhL5t0nJy5fyGHKrwNY)
   To: org.eclipse.ltk.ui.refactoring [3.5.0.v20100526-0800]
</pre>

**Comment by reprogrammer** [comment]
I'm surprised to see that our patch doesn't work on org.eclipse.ltk.ui.refactoring 3.5.0.v20100526-0800, because it's exactly the version that comes with Eclipse Helios and we've specifically targeted it.

Stas, can you check the installation details to see what features have been installed from our set of features? Specifically, we deliver four feature patches, two for Eclipse Helios and two other for Eclipse Helios SR1. Does Eclipse report that all four have been successfully installed?

By the way, I noticed that the error message has reported  the name of our project inconsistently as either "Coding Spectator" and "CodingSpectator". Nick and I have to fix this naming inconsistency as well.

**Comment by Wanderer777** [comment]
Mohsen, the only installation details that Eclipse provided to me are those that I've sent you (these details are copy/pasted above). It looks like nothing has been installed.

I see that you are very specific about the version of Eclipse in your patches. Although the version I used for smoke testing is Eclipse Helios, it is RC4. I wonder if that might be the cause of the problem.

**Comment by vazexqi** [comment]
Hmmm. The patches are extremely specific it seems, right to the last hash value!

We are targeting 

_3.6.0.v20100602-9gF78GpqFt6trOGhL60z0oEx3fz-JKNwxPY_

and Stas has 

_3.6.0.v20100602-9gF78GpqFt6trOGhL5t0nJy5fyGHKrwNY_

**Comment by vazexqi** [comment]
I've managed to solve this using the instructions at http://aniefer.blogspot.com/2009/06/patching-features-part-2.html and http://contraptionsforprogramming.blogspot.com/2009/09/groovy-eclipse-plugin-now-supports.html

However the question is: do we need to solve this problem? And would solving it this way bring about even worse consequences?

Remember a patch is supposed to be specific. What if in the next few months some other patch comes out that breaks our implementation in a weird way? And it's only this update that breaks it. Therefore our previous patches would work for the older versions... but for this next version we should create a different patch.

Creating different patches allows us to test things properly.

**Comment by reprogrammer** [comment]
We decided to target specific versions because of its simplicity. If our users have installed different versions of Eclipse, we'll ask them to download the ones that we support.
