### ISSUE TITLE
Set up a homepage for CodingSpectator

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#70]
We need to add more information to our static web page at GitHub. For example, we need to briefly describe the project, list the project members and upload the CodingSpectator manual.

**Comment by vazexqi** [comment]
How much information do you want to list? For instance, we don't want to talk too much about capturing refactorings since we don't want to bias the students. However, now that we have incorporated Stas's components, we are capturing more than just refactorings.

**Comment by reprogrammer** [comment]
Thanks for setting up the home page.
