### ISSUE TITLE
When users are debugging/running a new instance of Eclipse, our prompt might pop-up

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#71]
When users are debugging/running plug-ins for Photran in a new instance of Eclipse, they might actually see the pop-up dialog. This will 
1. annoy them since they will see it once everyday
2. confuse us since we now have a lot of spurious entries in the SVN repository.
3. might produce error if they have previously associated that working directory with a different username.

We also need to test this scenario with Stas's plug-in might incur additional overhead when run this way.

The easiest solution is to tell the users to configure the launch configuration so that it does not load our plug-in into the Eclipse runtime instance for running/debugging Photran.

**Comment by reprogrammer** [comment]
Yes, we should describe in the instructions how to disable our plug-in in their runtime workspace.

**Comment by vazexqi** [comment]
Already done in the updated user manual.

**Comment by vazexqi** [comment]
Due to some changes in the dependencies between plug-in, this method of changing the plug-ins that are loaded during the launch does not work anymore.

A temporary solution is to enable the TESTING_MODE environment variable while running. This will disabled the dialog from popping-up but will not disable the spurious logging. 

We need to find the root cause of this issue and solve it.

**Comment by reprogrammer** [comment]
The problem with setting the `TESTING_MODE` flag in the launch configuration is that we have to specify it for every single launch configuration. This has been quite annoying for Stas and I while working on Keshmesh. I wonder if there's a way to define a flag globally in Eclipse and share it with all launch configurations. If there's no substitute to adding the flag to every launch configuration, I suggest the following solution.

We can break the monitor plugin into two parts: ui and core. The ui takes care of the preferences page and startup events. And the core will take care of the submission, authentication and secure storage. As a result, codingtracker needs only to depend on monitor.core. So, the dependency jdt.ui -> codingtracker -> monitor.core won't contain the startup event. Therefore, excluding our plugin from the target platform will solve the issue for ever. Besides, the core/ui separation is a good move by itself as it brings about better decoupling.

**Comment by vazexqi** [comment]
I've split CodingSpectator into two parts (ui and the previous one). I have not updated the update_site or Stas's plug-in (but I no changes need to be made since it depends on the old edu.illinois.codingspectator.monitor which I did not rename).

See b729cf5ae10aa83bbe3ddfd02698cc93cac8134e

**Comment by reprogrammer** [comment]
Nick and I finished up the split in ef6b71d636b92b69b18cb8f94122ae247f1254fa.

**Comment by vazexqi** [comment]
Resolved in 6450eebb43f54a1d504ad5f6d424e751fbc14ac9

and updated in the user manual.
