### ISSUE TITLE
A dependency check prevents the installation of CodingSpectator

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#77]
We merged `codingtracker` into `master` and updated the feature patches. Then we built the feature and tried to install the feature from a local update site. But, we got the following error message while trying to install the feature.

<pre>
Cannot complete the install because of a conflicting dependency.
  Software being installed: CodingSpectator 1.0.0.201010141845 (edu.illinois.codingspectator.feature.feature.group 1.0.0.201010141845)
  Software currently installed: Eclipse for RCP and RAP Developers 1.3.0.20100617-0521 (epp.package.rcp 1.3.0.20100617-0521)
  Only one of the following can be installed at once: 
    Java Development Tools Core 3.6.0.v_A58 (org.eclipse.jdt.core 3.6.0.v_A58)
    Java Development Tools Core 3.6.1.v_A68_R36x (org.eclipse.jdt.core 3.6.1.v_A68_R36x)
  Only one of the following can be installed at once: 
    Navigator Workbench Components 3.4.201.M20100707-0800 (org.eclipse.ui.navigator.resources 3.4.201.M20100707-0800)
    Navigator Workbench Components 3.4.200.I20100601-0800 (org.eclipse.ui.navigator.resources 3.4.200.I20100601-0800)
  Cannot satisfy dependency:
    From: edu.illinois.codingspectator.codingtracker 1.0.0.201010141845 (edu.illinois.codingspectator.codingtracker 1.0.0.201010141845)
    To: bundle org.eclipse.jdt.core 3.6.1
  Cannot satisfy dependency:
    From: CodingSpectator 1.0.0.201010141845 (edu.illinois.codingspectator.feature.feature.group 1.0.0.201010141845)
    To: edu.illinois.codingspectator.codingtracker [1.0.0.201010141845]
  Cannot satisfy dependency:
    From: Eclipse for RCP and RAP Developers 1.3.0.20100617-0521 (epp.package.rcp 1.3.0.20100617-0521)
    To: org.eclipse.epp.package.rcp.feature.feature.group [1.3.0.20100617-0521]
  Cannot satisfy dependency:
    From: EPP RCP/RAP Feature 1.3.0.20100617-0521 (org.eclipse.epp.package.rcp.feature.feature.group 1.3.0.20100617-0521)
    To: org.eclipse.jdt.feature.group 3.6.0
  Cannot satisfy dependency:
    From: EPP RCP/RAP Feature 1.3.0.20100617-0521 (org.eclipse.epp.package.rcp.feature.feature.group 1.3.0.20100617-0521)
    To: org.eclipse.platform.feature.group [3.6.0.v20100602-9gF78GpqFt6trOGhL60z0oEx3fz-JKNwxPY]
  Cannot satisfy dependency:
    From: Eclipse Java Development Tools 3.6.0.v20100526-0800-7z8XFUJFMTfCWGoVuHImpms9H155 (org.eclipse.jdt.feature.group 3.6.0.v20100526-0800-7z8XFUJFMTfCWGoVuHImpms9H155)
    To: org.eclipse.jdt.core [3.6.0.v_A58]
  Cannot satisfy dependency:
    From: Eclipse Java Development Tools 3.6.1.r361_v20100714-0800-7z8XFUSFLFlmgLc5z-Bvrt8-HVkH (org.eclipse.jdt.feature.group 3.6.1.r361_v20100714-0800-7z8XFUSFLFlmgLc5z-Bvrt8-HVkH)
    To: org.eclipse.platform.feature.group 3.6.1
  Cannot satisfy dependency:
    From: Eclipse Platform 3.6.0.v20100602-9gF78GpqFt6trOGhL60z0oEx3fz-JKNwxPY (org.eclipse.platform.feature.group 3.6.0.v20100602-9gF78GpqFt6trOGhL60z0oEx3fz-JKNwxPY)
    To: org.eclipse.ui.navigator.resources [3.4.200.I20100601-0800]
  Cannot satisfy dependency:
    From: Eclipse Platform 3.6.1.r361_v20100909-9gF78GrkFqw7GrsZnvz0JWNTeb6fue6896L (org.eclipse.platform.feature.group 3.6.1.r361_v20100909-9gF78GrkFqw7GrsZnvz0JWNTeb6fue6896L)
    To: org.eclipse.ui.navigator.resources [3.4.201.M20100707-0800]</pre>

**Comment by vazexqi** [comment]
What has changed since the last update-site generation? That is the most probably culprit.

Also were you trying to install it on a clean instance of Eclipse? Or one that already had our plug-in?

**Comment by reprogrammer** [comment]
We tried to install it on a clean instance of Eclipse Helios.
The last time we built the update site was about a week ago when we asked some people to use our feature. Lots of things have changed since then. The most relevant are the ones we made to the feature and feature patches to include codingtracker.

Update: Note that we can successfully install it on Eclipse Helios SR1.

**Comment by vazexqi** [comment]
My guess is that we need to generate a patch for org.eclipse.ui.editors since Stas modified it. The rest of the dependencies aren't broken.

**Comment by reprogrammer** [comment]
`org.eclipse.ui.editors` is in the feature `org.eclipse.platform`. And, we already have a feature patch for `org.eclipse.platform`. Therefore, we just added `org.eclipse.ui.editors` to the list of plugins of the feature patches of `org.eclipse.platform`.

**Comment by reprogrammer** [comment]
I tried to install the two patches one by one to see which one is causing the dependency conflict. I was able to install the "Patch for LTK Helios". But, when I tried to install the "Patch for JDT Helios" I got the following error message.

`"Patch for JDT Helios" is not applicable to the current configuration and will not be installed.`

However, Eclipse doesn't give me any error messages when I try to install the "Patch for JDT Helios SR1" on Eclipse Helios. It puts the feature in the feature directory of eclipse but it doesn't put `org.eclipse.jdt.ui` into the plugins directory.

**Comment by reprogrammer** [comment]
I removed `edu.illinois.codingspectator.codingtracker` from `edu.illinois.codingspectator.feature`, `edu.illinois.codingspectator.platform.helios.patch` and `edu.illinois.codingspectator.platform.heliosSR1.patch`. Then, I removed the dependency from `org.eclipse.jdt.ui` to `edu.illinois.codingspectator.codingtracker` and reverted Stas' change to `org.eclipse.jdt.ui`. Making these removals enabled me to successfully build the update site and install it on a clean instance of Eclipse Helios.

**Comment by reprogrammer** [comment]
I added `edu.illinois.codingspectator.codingtracker` back to `edu.illinois.codingspectator.feature`, `edu.illinois.codingspectator.platform.helios.patch` and `edu.illinois.codingspectator.platform.heliosSR1.patch`. But, I made sure that there is no dependency from `org.eclipse.jdt.ui` to `edu.illinois.codingspectator.codingtracker`. At the end, I still get the same dependency conflict error. This test shows that removing the dependency from `org.eclipse.jdt.ui` to `edu.illinois.codingspectator.codingtracker` doesn't solve the problem.

Surprisingly, this configuration allowed me to install on Eclipse Helios SR1.

**Comment by reprogrammer** [comment]
I increased the version number of `org.eclipse.ui.editors` from 3.6.1.x to 3.9.1.x. But, that didn't solve the problem.

**Comment by reprogrammer** [comment]
Stas, I noticed that you've used the version of `org.eclipse.ui.editors` that comes with Ecilpse Helios SR1. Could you try using the one that comes with Eclipse Helios? Since I've had trouble installing codingtracker on Eclipse Helios but not Eclipse Helios SR1, you might just need to use an older version of `org.eclipse.ui.editors`. Also, increase the version number of `org.eclipse.ui.editors` as I did. We've found it to be sometimes necessary for the feature patching mechanism to work. Please try these fixes in the `codingtracker` branch not in the master branch.

**Comment by reprogrammer** [comment]
The problem was that codingtracker was required a minimum version of 3.6.1 for several plug-ins such as `jdt.core`. This caused the dependency conflict on Eclipse Helios as it refused to install both `jdt.core 3.6.0.x` and `jdt.core 3.6.1.y`. We also replaced `org.eclipse.ui.editors` by the version that comes with Eclipse Helios. But, we suspect that the latter change was the root cause of the problem.

**Comment by reprogrammer** [comment]
Resolved by 6e3d9daf521dd1066428be5f12cbcf86f4b8ec3f.
