### ISSUE TITLE
Disable debug statements

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#79]
codingtracker and monitor print some debugging information to the console. I suggest to use a flag such as `DEBUGGING_MODE` in the launch configuration to decide whether or not to print out the debug statements. Please see the `TESTING_MODE` flag in monitor.test for an example.

**Comment by reprogrammer** [comment]
Stas wants to enable this switch during development and not deployment. So, an option in the launch configuration would be sufficient. And, we don't need to devote a property to it.

**Comment by Wanderer777** [comment]
Resolved in codingtracker by b675f873b6c3fc0fe3cdd93b5c3f6876069d2798

**Comment by reprogrammer** [comment]
Resolved in CodingSpectator by 4fef3d342c632d2019a8ebb8f7310baf026b36bf.
