### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#80]
I installed CodingSpectator 1.0.0.201010151736 on Eclipse Helios SR1 of my Linux laptop successfully. And, the authentication prompter popped up when I restarted Eclipse. Then, I installed Findbugs 1.3.9.20090821. When the installation of Findbugs finishes, I got the following error message.

<pre>
Cannot complete the install because one or more required items could not be found.
Software currently installed: CodingSpectator 1.0.0.201010151736 (edu.illinois.codingspectator.feature.feature.group 1.0.0.201010151736)
Missing requirement: Patch for JDT Helios 1.0.0.201010151736 (edu.illinois.codingspectator.jdt.helios.patch.feature.group 1.0.0.201010151736) requires 'org.eclipse.jdt.feature.group [3.6.0.v20100526-0800-7z8XFUJFMTfCWGoVuHImpms9H155]' but it could not be found
Cannot satisfy dependency:
From: CodingSpectator 1.0.0.201010151736 (edu.illinois.codingspectator.feature.feature.group 1.0.0.201010151736)
To: edu.illinois.codingspectator.jdt.helios.patch.feature.group [1.0.0.201010151736]
</pre>

Since I'm using Helios SR1 the fact that the error message warns about the missing dependency to the patch for JDT Helios is strange. This is a severe problem as it prevents me from installing Findbugs on my Eclipse. It looks like that Eclipse checks the dependency to the patch for JDT Helios when trying to install plug-ins after the installation of CodingSpectator.

**Comment by reprogrammer** [comment]
I'll mark the feature patches as optional and see if the problem persists.

**Comment by vazexqi** [comment]
We need to try this not only on a "clean" installation but also a typical installation of Eclipse that the students will be using.

This means that we should follow the instructions from CS427 and ensure that Subclipse is installed. They might also be using ECLEmma or some other metric thing.

Findbugs was in the Photran Developer's Guide as a recommendation but I (hope) don't think that students will install it. However some other developers might have that installed.

**Comment by reprogrammer** [comment]
Resolved by 1602b0debf76ee97d185960fcd2b3e8b7f7fb36f.
