### ISSUE TITLE
Create a SWTBot plug-in test for Extract Method

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#81]
So far, we haven't been able to find out how to an automated GUI test for the extract method refactoring. I suggest that we submit this issue as a bug report to the SWTBot team.

**Comment by reprogrammer** [comment]
Aaron Digulla has replied to our [stackoverflow](http://stackoverflow.com/questions/3706225/why-is-a-menu-item-disabled-when-using-swtbot/3873820#3873820) post. We need to verify his suggestion.

Aaron's suggestion didn't fix the problem.

**Comment by reprogrammer** [comment]
We filed a bug report at https://bugs.eclipse.org/bugs/show_bug.cgi?id=333512.

**Comment by reprogrammer** [comment]
We hacked up `ExtractMethodAction` to always enable the extract method menu item when running in test mode. This hack enables SWTBot to test extract method.

**Comment by vazexqi** [comment]
I think this issue can be closed. We have incorporated the prototype that I had written into a test suite. Check the other "Test" (https://github.com/vazexqi/CodingSpectator/issues/labels/Test) issues in the list.
