### ISSUE TITLE
No repository found

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#82]
I successfully installed CodingSpectator v1.0.0.201010151736 on a clean instance of Helios SR1 on my Linux laptop. Then, I tried to install Subversive. But, it failed to install with the following error message.

<pre>
An error occurred while collecting items to be installed
session context was:(profile=epp.package.rcp, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.team.svn,0.7.9.I20100512-1900
No repository found containing: osgi.bundle,org.eclipse.team.svn.core,0.7.9.I20100512-1900
No repository found containing: org.eclipse.update.feature,org.eclipse.team.svn,0.7.9.I20100512-1900
No repository found containing: osgi.bundle,org.eclipse.team.svn.help,0.7.9.I20100512-1900
No repository found containing: osgi.bundle,org.eclipse.team.svn.mylyn,0.7.9.I20100512-1900
No repository found containing: org.eclipse.update.feature,org.eclipse.team.svn.mylyn,0.7.9.I20100512-1900
No repository found containing: osgi.bundle,org.eclipse.team.svn.resource.ignore.rules.jdt,0.7.9.I20100512-1900
No repository found containing: org.eclipse.update.feature,org.eclipse.team.svn.resource.ignore.rules.jdt,0.7.9.I20100512-1900
No repository found containing: osgi.bundle,org.eclipse.team.svn.ui,0.7.9.I20100512-1900
</pre>

It's funny that when it tries to install Subversive it includes our IL/NCSA license on the license page. I suspect that the root cause of this failure is the same as that of issue #80.

**Comment by vazexqi** [comment]
What happens if Subversive is already installed?

I suspect what is happening is the fact that we changed Eclipse epp/core through our patch and now it cannot find the packages because our patch does not contain a proper  update site. It only lists codingspectatot.github.com which does not contain the packages.

**Comment by reprogrammer** [comment]
I successfully installed Subversive after the installation of CodingSpectator v1.0.0.201010151736 on a fresh Eclipse Helios SR1.

By the way, the update site URL for the feature patch projects is empty. But the "Included Features" tab of the `edu.illinois.codingspectator.feature` has the following options for each included feature patch.

<pre>
When searching for patches to this included feature, contact
1. the update site for the parent feature
2. the update site for the included feature
3. both
</pre>


Currently, the first option is selected for our feature patches.

**Comment by reprogrammer** [comment]
This issue is resolved by 1602b0debf76ee97d185960fcd2b3e8b7f7fb36f.
