### ISSUE TITLE
Missing events during data upload

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#84]
SVN acquires a lock at the beginning of the commit operation and reverts the contents of the log files back to the ones at the time of acquiring the lock. If the data upload operation takes a while to finish and the user performs some events that we'd like to capture during the upload operation, we'll miss those events. 

The only solution that I can think is to separate the location of log files from the SVN working copy. That is, whenever an interesting event occurs, we'll store it immediately in a log file that is not in the working copy. And, whenever a data uploads initiates, we first copy the log files into the working copy. Stas has implemented a similar solution in codingtracker.

**Comment by vazexqi** [comment]
How did you test this? By uploading a test file that is a couple of MBs?

**Comment by reprogrammer** [comment]
We should think of a way to test this scenario. But, Stas experience shows that such a scenario may be possible. I've opened this issue so that we keep this possible problem in mind. However, it isn't of a high priority at the moment.

**Comment by reprogrammer** [comment]
Stas has fixed this issue. Basically, after `svn add` and before `svn commit`, he creates a temporary file in the same directory that the main file is. And, while `svn commit` is in progress, he writes data into the temporary file whenever he wants to record some data. Finally, when `svn commit` is finished, he copies the data in the temporary file back into the main file and deletes the temporary file.
