### ISSUE TITLE
Check the validity of edit sequences

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#85]
CodingTracker records find-grained events and Stas likes it to be really precise. However, there are lots of corner cases that might cause some imprecision in the data that CodingTracker records. Currently, Stas is looking for such corner cases in an ad-hoc fashion and tries to address each corner case that he can think of. Apparently, users might reveal new corner cases that break the edit sequence. So, Stas is going to implement some mechanisms to check the validity of the captured edit sequence. One way to detect problems in the edit sequence is to take snapshots of files regularly, e.g. every time the user commits changes to the repository. Having these snapshots, a replayer could compare the result of applying the edit sequence to a particular snapshot. If the edit sequence is different from the taken snapshot, there is something wrong with either the edit sequence or the snapshot.

**Comment by vazexqi** [comment]
So this will be a fallback mechanism. Seems like a good idea.

Will this be turned on by default? 
What is the overhead of these additional snapshots?

**Comment by Wanderer777** [comment]
Yes, I think it should be on by default. The overhead depends on how often a programmer commits and how big the committed files are. Anyway, this should be dwarfed by the overhead of keeping track of every code edit. 

This fallback mechanism is coarse grained both from the point of view of the snapshot size (entire file), and the time interval (commits happen not that often). But there is one more, much finer mechanism that allows to check validity of a code edits sequence. For every edit, besides the new text, the offset, and the length of the replaced text, the logger logs the replaced text (i.e. the old text). A replayer can compare the replaced text with the actual text at the corresponding offset and length and immediately detect that a particular sequence is broken if the actual and the replaced text differ.

**Comment by Wanderer777** [comment]
This issue is resolved by b7aaa14d6b9693899dd4cc1fa186acc81c31e50c
