### ISSUE TITLE
Use org.eclipse.compare that comes with Eclipse Helios

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#88]
According to conventions we set up for creating feature patches mentioned #87, we need to replace the `org.eclipse.compare` plugin in CodingSpectator by the one that comes with Eclipse Helios not Eclipse Helios SR1.

**Comment by Wanderer777** [comment]
Fixed by 92d5dfb496c685ee3e34e1aad9850c008095e636
