### ISSUE TITLE
Consolidate logs files of captured refactorings into a single log file

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#95]
CodingSpectator doesn't log all refactorings in a single file. Rather, they are scattered through out several XML files. These XML files are stored in nested directory structures that reflect the date on which the refactorings have been performed.

In order to make sense of the refactorings and analyze them, we have to first gather the refactorings in a single file. Then, we can either use Excel to analyze the resulting XML file or convert the XML file to some other format that makes some analysis or visualization possible.

We'd like to merge the refactorings into a single XML file as follows. Given a directory `dir`, the log consolidator looks for all `refactoring.history` files in `dir` recursively. Each `refactoring.history` has a top level `session` tag. The log consolidator will copy all these XMLs into a single XML that wraps all `session` tags in a top level `sessions` tag.

**Comment by albaloo** [comment]
Resolved by  75cc1d88a643d9be272a2c2a488b1a89d788565f.

**Comment by reprogrammer** [comment]
The current program only looks for `refactoring.history` under `performed` and `canceled` directories. We also save the refactorings that Eclipse records under the `.refactorings` directory. We might need to analyze these refactorings as well. Therefore, I suggest to make the log file consolidator more configurable by accepting switches that determine what directories to consolidate: `performed`, `canceled` and `.refactorings`.

**Comment by albaloo** [comment]
Made the log consolidator more generic in da4085c019af3eabb3538fff8e142c57fb443943.
