### ISSUE TITLE
Monitor Copy and Delete Refactoring Participants?

### ISSUE THREAD

**Issue by vazexqi** [vazexqi/CodingSpectator#97]
We need to decide if we are going to monitor the copy and delete refactorings. Right now, we are not sure whether they are involved as "stepping stones" in any of the bigger refactorings such as Pull Up refactoring. If they are, we might need to capture them so that we can capture the entire refactoring process.

**Comment by reprogrammer** [comment]
Now, we know that the pull up refactoring is standalone and doesn't depend on copy and delete refactorings.

**Comment by reprogrammer** [comment]
Because copy and delete are not refactorings, we decided not to monitor them.
