### ISSUE TITLE
Fetch the SVNKit jar files automatically

### ISSUE THREAD

**Issue by reprogrammer** [vazexqi/CodingSpectator#99]
Right now, if someone checks out our source code from our repository, he/she won't get the SVNKit plugin. We excluded it from our repository because it's simply a bunch of jar files. Therefore, I suggest to write a Ruby script or something that downloads the necessary files from svnkit.org and fills up the plugin with the required jar files.

**Comment by vazexqi** [comment]
Can we just check-in the jar files directly into the repository? That would make everything easier. If we use a Ruby script the user would have to remember to run that script again initially requiring a more complicated process.

**Comment by reprogrammer** [comment]
We could simply check-in the jar files. Some people check third-party jar files into their repositories and some use Maven, Ivy, etc. (See http://stackoverflow.com/questions/603247/should-libraries-jar-go-into-the-repository). I prefer not to check in the jar files into the repository just because they are not our artifacts and binary files tend to pollute repositories. I'm proposing a Ruby script as an alternative to Maven configuration files. I've seen several projects using such scripts to fetch binary dependencies, e.g. X10 and WALA. I think if we document the script in our "environmnet setup" document, there won't be any confusion.

**Comment by reprogrammer** [comment]
I added the SVNKit plugin project and wrote a Ruby script to fetch the SVNKit jar files. The commit ded308ee31dd947ef548562de3cec53c6e51dcb0 from the branch `fetch-svnkit-jars` makes these changes. If we like this commit, we'll merge it into the master branch.

By the way, I noticed that SVNKit has a Maven repository. But, I'm not a big fan of using Maven just for one library.

**Comment by vazexqi** [comment]
See cc6c9ae32e3436b9fa020ef9f86c90332627abe2

This uses an ant script. I have also hooked into the Eclipse build process so the files will be fetched automatically upon a build (if necessary).

I'm not that familiar with Ant so there might be better ways to do this. However, if we are going to use a script to do this, we should use Ant by default and not add unnecessary dependencies to Ruby. Moreover the way the Ruby script is written assume the presence of 
1. a *nix environment (through the shebang line)
2. the presence of sha1sum

I have left your Ruby file in there just for reference.

**Comment by reprogrammer** [comment]
I'm perfectly fine with an Ant build file since it integrates with Eclipse better. In general, I'd rather use Ant files when they just work. But, I don't like to debug or write them!

My only suggestion is to use the [Ant checksum task](http://ant.apache.org/manual/Tasks/checksum.html) to check the integrity of the download.

**Comment by vazexqi** [comment]
I've adde the checksum task in 3ac2c4644971d732cf386d5e66b26c8f8a8c0b87
but it does not seem to care if the checksum has been tampered. I am not sure what is wrong so if you can take a look please do.

Either way, the checksum task is not essential and we can merge cc6c9ae32e3436b9fa020ef9f86c90332627abe2 into master first while we debug this particular setback.

Having the current ant file in master seems to be useful.

**Comment by reprogrammer** [comment]
Fixed the checksum in 9a8be2968a6bcb51381017dbd0ccaa6570e407cc. The list of jar files is duplicated throughout the ant script and I don't know how to get rid of it.
